import type { Locale } from './i18n';
export type ArticleLocale = 'en' | 'es';

export const articles = [
  {
    id: 'spot-bubble',
    slug: { en: 'how-to-spot-a-stock-market-bubble', es: 'como-detectar-una-burbuja-bursatil' },
    en: {
      kicker: 'BUBBLE BASICS', title: 'How to spot a stock market bubble',
      description: 'Learn the clearest signs of a stock market bubble, from stretched valuations and leverage to investor positioning, credit and complacency.',
      intro: 'Bubbles rarely announce themselves with one perfect number. They emerge when expensive prices, easy financing and confident behavior begin reinforcing one another.',
      sections: [
        ['Start with valuation, not headlines', 'High prices alone do not prove a bubble. Compare prices with durable earning power and the size of the economy. Shiller CAPE and market value to GDP are slow-moving gauges that reveal when optimism has become historically expensive.'],
        ['Look for fuel', 'Leverage turns enthusiasm into fragility. Fast-rising margin debt means more investors are borrowing against securities, which can amplify gains on the way up and forced selling on the way down.'],
        ['Demand confirmation', 'Positioning, credit spreads and volatility show whether investors and lenders are behaving as if risk has disappeared. A convincing bubble signal is broad: several independent gauges should be hot at the same time.']
      ]
    },
    es: {
      kicker: 'CONCEPTOS BÁSICOS', title: 'Cómo detectar una burbuja bursátil',
      description: 'Aprende las señales más claras de una burbuja bursátil: valoración, apalancamiento, posicionamiento, crédito y complacencia.',
      intro: 'Las burbujas casi nunca se anuncian con un único número perfecto. Aparecen cuando los precios caros, la financiación fácil y la confianza se refuerzan mutuamente.',
      sections: [
        ['Empieza por la valoración, no por los titulares', 'Los precios altos por sí solos no demuestran una burbuja. Compáralos con los beneficios sostenibles y el tamaño de la economía. El CAPE de Shiller y el valor de mercado frente al PIB muestran cuándo el optimismo se ha vuelto históricamente caro.'],
        ['Busca el combustible', 'El apalancamiento convierte el entusiasmo en fragilidad. Un crecimiento rápido de la deuda de margen implica más dinero prestado contra valores, lo que amplifica las subidas y las ventas forzadas durante una caída.'],
        ['Exige confirmación', 'El posicionamiento, los diferenciales de crédito y la volatilidad indican si inversores y prestamistas actúan como si el riesgo hubiera desaparecido. Una señal convincente debe ser amplia: varios indicadores independientes tienen que calentarse a la vez.']
      ]
    }
  },
  {
    id: 'cape',
    slug: { en: 'what-is-the-shiller-cape-ratio', es: 'que-es-el-ratio-cape-de-shiller' },
    en: {
      kicker: 'VALUATION GUIDE', title: 'What is the Shiller CAPE ratio?',
      description: 'A plain-English guide to the Shiller CAPE ratio, what it measures, its historical bubble signals and the limits investors should understand.',
      intro: 'The Shiller CAPE asks a deliberately patient question: how much are investors paying for a decade of inflation-adjusted corporate earnings?',
      sections: [
        ['Why use ten years of earnings?', 'One year of profits can be distorted by a recession, a boom or an unusual shock. Averaging ten inflation-adjusted years smooths the cycle and makes comparisons across market eras more useful.'],
        ['What counts as expensive?', 'There is no magic cutoff, but readings above 30 have historically belonged to a rare and expensive part of the distribution. The dot-com peak was much higher; other costly markets corrected without matching it.'],
        ['What CAPE cannot tell you', 'CAPE is poor at timing. An expensive market can become more expensive and remain there for years. Use it as a pressure gauge, then look to leverage, positioning, credit and sentiment for confirmation.']
      ]
    },
    es: {
      kicker: 'GUÍA DE VALORACIÓN', title: '¿Qué es el ratio CAPE de Shiller?',
      description: 'Guía clara sobre el CAPE de Shiller: qué mide, sus señales históricas de burbuja y los límites que todo inversor debe conocer.',
      intro: 'El CAPE de Shiller plantea una pregunta deliberadamente paciente: ¿cuánto pagan los inversores por una década de beneficios empresariales ajustados por inflación?',
      sections: [
        ['¿Por qué usar diez años de beneficios?', 'Un solo año puede estar distorsionado por una recesión, un auge o un choque excepcional. La media de diez años ajustados por inflación suaviza el ciclo y permite comparar épocas distintas.'],
        ['¿Qué se considera caro?', 'No existe un umbral mágico, pero las lecturas superiores a 30 han ocupado históricamente una zona rara y cara. El máximo puntocom fue mucho mayor; otros mercados costosos corrigieron sin alcanzarlo.'],
        ['Lo que el CAPE no puede decir', 'El CAPE no sirve para anticipar fechas. Un mercado caro puede encarecerse y seguir así durante años. Úsalo como indicador de presión y busca confirmación en el apalancamiento, el posicionamiento, el crédito y el sentimiento.']
      ]
    }
  },
  {
    id: 'margin-debt',
    slug: { en: 'margin-debt-and-stock-market-bubbles', es: 'deuda-de-margen-y-burbujas-bursatiles' },
    en: {
      kicker: 'LEVERAGE GUIDE', title: 'Margin debt and stock market bubbles',
      description: 'Understand how FINRA margin debt can amplify stock market bubbles, why its rate of change matters and what the indicator cannot predict.',
      intro: 'Margin debt is money investors borrow against securities in their brokerage accounts. It is both a measure of confidence and a source of forced selling.',
      sections: [
        ['Why acceleration matters', 'The dollar level naturally grows with the market and the economy, so the pace of change is often more informative. Rapid year-over-year growth suggests that risk-taking is accelerating rather than merely keeping up.'],
        ['The feedback loop', 'Borrowing can lift demand and prices, which increases collateral values and enables more borrowing. When prices fall, the loop can reverse through margin calls and compulsory sales.'],
        ['Read it beside valuation', 'Margin debt is not a standalone sell signal. Rising leverage is most concerning when valuations are already stretched and lenders and investors remain unusually relaxed about risk.']
      ]
    },
    es: {
      kicker: 'GUÍA DE APALANCAMIENTO', title: 'Deuda de margen y burbujas bursátiles',
      description: 'Entiende cómo la deuda de margen de FINRA puede amplificar una burbuja, por qué importa su crecimiento y qué no puede predecir.',
      intro: 'La deuda de margen es el dinero que los inversores piden prestado contra los valores de sus cuentas. Mide confianza y también puede provocar ventas forzadas.',
      sections: [
        ['Por qué importa la aceleración', 'El nivel en dólares crece de forma natural con el mercado y la economía, por lo que el ritmo de cambio suele ser más informativo. Un aumento interanual rápido indica que la toma de riesgo se acelera.'],
        ['El círculo de retroalimentación', 'El crédito puede elevar la demanda y los precios, aumentando el valor del colateral y permitiendo pedir aún más prestado. Cuando los precios caen, el círculo se invierte mediante llamadas de margen y ventas obligatorias.'],
        ['Léela junto a la valoración', 'La deuda de margen no es una señal de venta independiente. El apalancamiento preocupa más cuando la valoración ya está tensionada y prestamistas e inversores siguen demasiado tranquilos ante el riesgo.']
      ]
    }
  },
  {
    id: 'methodology',
    slug: { en: 'how-our-bubble-indicator-works', es: 'como-funciona-el-indicador-de-burbuja' },
    en: {
      kicker: 'METHODOLOGY', title: 'How our bubble indicator works',
      description: 'See how our stock market bubble indicator combines six signals, why valuation and leverage come first, and what each weight contributes.',
      intro: 'The indicator is a structured argument, not a forecast. It asks whether expensive prices, leverage and confident risk-taking are appearing together—and makes every judgment visible.',
      sections: [
        ['From six readings to one score', 'Each signal is clamped to a 0–100 pressure score using a fixed range: CAPE 18–42, market value to GDP 80–240%, margin-debt growth −10–40%, household equity allocation 25–50%, credit spreads 4.5–1.5% and VIX 30–10. The last two run in reverse because lower readings imply more complacency. We multiply those scores by their weights and add them. The composite becomes NO below 30, NOT YET at 30, MAYBE at 45, PROBABLY at 60 and YES at 75.'],
        ['First priority: valuation · 45%', 'Valuation gets the largest share because detachment from economic fundamentals is the defining ingredient of a bubble. Shiller CAPE receives 25% and market value to GDP 20%. CAPE compares prices with smoothed earning power; market value to GDP compares the whole market with the economy supporting it. Using both keeps one valuation lens from deciding the verdict alone.'],
        ['Second priority: leverage · 25%', 'Margin debt receives 25%, equal to the largest single valuation signal. Borrowing does more than accompany optimism: it can amplify demand on the way up and force selling when collateral falls. We score its year-over-year growth rather than its dollar level, because the level naturally rises as markets and the economy grow.'],
        ['Confirmation signals · 30%', 'The remaining signals test whether the enthusiasm is broad. Credit spreads receive 12% because lenders provide an independent market price for risk. Household equity allocation receives 10% because crowded ownership leaves less uncommitted buying power. The VIX receives 8%, the smallest weight, because short-term calm can be useful confirmation but is noisy and can reverse quickly.'],
        ['Why the weights are not probabilities', 'The weights express priority, not the chance of a crash: 25% does not mean a signal predicts one quarter of market outcomes. Slow-moving fundamentals and leverage carry 70% so a fleeting mood cannot dominate the result. A separate confidence measure checks how closely the six signals agree and how far the composite sits from the next decision boundary. Read the score as a transparent temperature check, never as a market-timing rule.']
      ]
    },
    es: {
      kicker: 'METODOLOGÍA', title: 'Cómo funciona el indicador de burbuja',
      description: 'Descubre cómo nuestro indicador de burbuja bursátil combina seis señales, por qué prioriza valoración y apalancamiento y qué aporta cada peso.',
      intro: 'El indicador es un argumento estructurado, no una predicción. Pregunta si los precios caros, el apalancamiento y la confianza ante el riesgo aparecen a la vez, y deja cada decisión a la vista.',
      sections: [
        ['De seis lecturas a una puntuación', 'Cada señal se limita a una puntuación de presión de 0 a 100 con un rango fijo: CAPE 18–42, valor de mercado/PIB 80–240%, crecimiento de la deuda de margen −10–40%, asignación familiar a bolsa 25–50%, diferenciales de crédito 4,5–1,5% y VIX 30–10. Los dos últimos se invierten porque una lectura menor implica más complacencia. Multiplicamos las puntuaciones por sus pesos y las sumamos. El índice dice NO por debajo de 30, TODAVÍA NO desde 30, QUIZÁ desde 45, PROBABLEMENTE desde 60 y SÍ desde 75.'],
        ['Primera prioridad: valoración · 45%', 'La valoración recibe el mayor peso porque la separación respecto a los fundamentos económicos es el ingrediente esencial de una burbuja. El CAPE de Shiller aporta un 25% y el valor de mercado frente al PIB un 20%. El CAPE compara precios con beneficios suavizados; el segundo compara todo el mercado con la economía que lo sostiene. Usar ambos evita que una sola perspectiva decida el resultado.'],
        ['Segunda prioridad: apalancamiento · 25%', 'La deuda de margen aporta un 25%, igual que la mayor señal de valoración. El crédito no solo acompaña al optimismo: puede amplificar la demanda durante la subida y forzar ventas cuando cae el valor del colateral. Medimos su crecimiento interanual, no el nivel en dólares, porque ese nivel aumenta de forma natural con el mercado y la economía.'],
        ['Señales de confirmación · 30%', 'Las señales restantes comprueban si el entusiasmo es amplio. Los diferenciales de crédito pesan un 12% porque los prestamistas aportan un precio del riesgo independiente. La asignación familiar a bolsa pesa un 10% porque un posicionamiento saturado deja menos compradores disponibles. El VIX pesa un 8%, el mínimo, porque la calma a corto plazo confirma el contexto, pero es ruidosa y puede cambiar rápido.'],
        ['Los pesos no son probabilidades', 'Los pesos expresan prioridad, no la probabilidad de una caída: un 25% no significa que una señal explique la cuarta parte de los resultados del mercado. Los fundamentales lentos y el apalancamiento suman un 70% para que un cambio fugaz de ánimo no domine el índice. Una medida de confianza separada evalúa cuánto coinciden las seis señales y a qué distancia está el resultado del siguiente umbral. Léelo como un termómetro transparente, nunca como una regla para anticipar el mercado.']
      ]
    }
  },
  {
    id: 'how-long-do-stock-market-bubbles-last',
    slug: {
      en: 'how-long-do-stock-market-bubbles-last',
      es: 'how-long-do-stock-market-bubbles-last',
    },
    en: {
      kicker: '',
      title: 'How Long Do Stock Market Bubbles Last?',
      description: 'Compare the duration of major stock market bubbles, why warnings arrive early, and which signs may show a speculative boom is nearing its peak.',
      intro: 'Compare the duration of major stock market bubbles, why warnings arrive early, and which signs may show a speculative boom is nearing its peak.',
      sections: [
        ['What counts as a stock market bubble—and when does it begin?', 'A stock market bubble begins when prices become increasingly detached from plausible fundamentals and are sustained mainly by expectations of further price gains. There is no official starting date, so bubble timelines depend on whether the clock begins with the broader bull market, the break from fundamentals, or the final speculative surge.\n\nEconomist Joseph Stiglitz offered a widely used definition in a 1990 *Journal of Economic Perspectives* paper: a bubble exists when a high price is driven by investors’ belief that they can sell at an even higher price, rather than by factors that justify the price itself.\n\nThat definition explains why bubbles are easier to date after they burst. Earnings can improve, interest rates can fall, and new technology can support higher prices for legitimate reasons before speculation takes over. Analysts may therefore agree on the peak while choosing very different starting points.\n\nA practical timeline should identify its rule explicitly. Possible starting markers include:\n\n- The beginning of the bull market that eventually produced the bubble.\n- The point at which valuations moved far above their historical range.\n- The start of rapid price acceleration or widespread speculative participation.\n- A recognizable change in leverage, issuance, trading activity, or investor behavior.\n\nThese markers are part of a broader framework for [spotting a stock market bubble](https://www.areweinabubbleyet.com/learn/how-to-spot-a-stock-market-bubble/), but none can establish a universally accepted start date by itself.'],
        ['How long did major stock market bubbles last historically?', 'Historical stock market bubbles have lasted anywhere from several months to roughly eight years, depending on the episode and the starting point used. Their most speculative final phases were usually much shorter than the bull markets that preceded them.\n\nThe following stock market bubble timeline uses a clearly stated reference period for each episode rather than pretending that every day of the ascent was necessarily a bubble.\n\n| Episode | Timeline used | Approximate duration to peak | What the historical record shows |\n|---|---|---:|---|\n| South Sea Bubble | January to August 1720 | 7 months | The Bank of England’s historical account says South Sea Company shares rose from about £128 in January to roughly £1,000 in August, then fell to about £124 by December. This was a company-centered mania rather than a modern broad-market index bubble. |\n| U.S. market of the 1920s | August 1921 to September 1929 | 8 years | Federal Reserve History reports that the Dow Jones Industrial Average rose sixfold, from 63 in August 1921 to 381 in September 1929. The full period was a bull market; the clearly speculative phase came later. |\n| Japanese asset bubble | 1985 to December 1989 | About 4 years | The International Monetary Fund has noted that Japanese stock prices roughly tripled between 1985 and 1989. Nikkei historical data place the index’s record close at 38,915.87 on December 29, 1989. |\n| Dot-com bubble | January 1995 to March 2000 | About 5 years | Nasdaq data published through the Federal Reserve Bank of St. Louis show the Composite rising from about 752 at the start of 1995 to 5,048.62 on March 10, 2000. |\n| Chinese equity boom | Mid-2014 to mid-June 2015 | About 1 year | The Bank for International Settlements reported that Chinese stock prices gained about 125% from mid-2014 to their 2015 peak, with leveraged trading helping to amplify the rise. |\n\nThese cases should not be averaged into a typical bubble lifespan. They involved different market structures, monetary conditions, valuation methods, and levels of leverage. The comparison instead shows that high prices can persist for years, while the final rush into the market may last only months.'],
        ['Why can bubbles keep growing after warning signs appear?', 'Bubbles can continue because a warning sign identifies vulnerability, not the event that will force investors to sell. Prices may keep rising while liquidity remains abundant, earnings narratives stay credible, and buyers expect to exit before everyone else.\n\nThe dot-com period provides a clear example. Federal Reserve Chair Alan Greenspan warned about *irrational exuberance* on December 5, 1996, but Nasdaq data show that the Composite subsequently rose from around 1,300 to more than 5,000 before peaking in March 2000. A prominent valuation warning arrived more than three years before the top.\n\nSeveral forces can prolong the rise:\n\n- **Momentum attracts new buyers.** Strong recent returns can be interpreted as confirmation that optimistic forecasts are correct.\n- **Fundamentals may initially improve.** Genuine innovation, revenue growth, or falling interest rates can support part of the advance even when prices later overshoot.\n- **Short sellers face timing risk.** A security can become more overvalued before it falls, creating potentially large losses for investors betting against it.\n- **Benchmark pressure encourages participation.** Professional managers who avoid a rapidly rising sector may underperform before the bubble breaks.\n- **Credit expands purchasing power.** Borrowed money allows demand to grow faster than investors’ cash resources.\n\nThis is why valuation measures should not be used as countdown clocks. They can indicate that expected long-term returns are less attractive or that the market is vulnerable, but they cannot specify the peak date.'],
        ['Which warning signs suggest a bubble may be nearing its end?', 'A bubble may be nearing its end when extreme valuation is joined by accelerating prices, rising leverage, speculative issuance, weakening market breadth, and tighter financial conditions. No single signal reliably identifies the exact top, but several deteriorating together deserve more attention than one elevated ratio.\n\nImportant late-stage signs include:\n\n- **Near-vertical price gains.** A sharp acceleration can indicate that expectations and momentum, rather than incremental fundamental news, are driving returns.\n- **Prices outrunning business results.** Valuations become more fragile when share prices rise much faster than sales, earnings, or cash flow across a large part of the market.\n- **Rapid growth in borrowed investing.** Leverage can magnify gains on the way up and create forced selling when prices fall. The site’s guide to [margin debt and stock market bubbles](https://www.areweinabubbleyet.com/learn/margin-debt-and-stock-market-bubbles/) explains why the direction and rate of change may matter more than a single debt level.\n- **A surge in speculative offerings.** Jay Ritter’s IPO research at the University of Florida records an average first-day return of 71.7% for U.S. IPOs in 1999, illustrating the intense demand for newly listed companies near the dot-com peak.\n- **Narrowing participation.** An index can keep rising even as fewer stocks participate, leaving performance dependent on a small number of market leaders.\n- **Tighter liquidity.** Federal Reserve records show that the federal funds target rose from 4.75% before June 1999 to 6.5% in May 2000. The Nasdaq peaked during that tightening cycle, although rate increases alone did not determine the peak.\n- **Failure to respond to good news.** When optimistic announcements no longer produce lasting gains, it may indicate that buyers are becoming exhausted.\n\nStock market bubbles burst when enough investors revise their expectations at the same time and marginal demand disappears. The trigger may be disappointing earnings, tighter credit, regulation, fraud, or no single identifiable event; what matters is that confidence and available financing no longer support the prevailing price.'],
        ['What typically happens when a stock market bubble bursts?', 'When a bubble bursts, prices usually fall faster than they rose during the early part of the boom, but the full decline can unfold through repeated crashes and temporary rallies. Recovery time varies from months to decades and is often much longer than the initial sell-off.\n\nNasdaq’s dot-com decline demonstrates the difference between the first break and the complete unwind. Federal Reserve Bank of St. Louis data show that the Composite fell from 5,048.62 on March 10, 2000 to 1,114.11 on October 9, 2002—a decline of about 78% over 31 months.\n\nThe 1929 episode was similarly prolonged. Federal Reserve History records a 381 Dow peak in September 1929, while S&P Dow Jones Indices places the eventual low at 41.22 in July 1932, approximately 89% below the peak.\n\nJapan illustrates how long the recovery can take. After closing at 38,915.87 in December 1989, the Nikkei 225 did not surpass that nominal closing record until February 2024, according to Nikkei index records.\n\nA typical unwind may include an abrupt break, forced selling by leveraged investors, a rebound that appears to mark the bottom, and further declines as earnings forecasts adjust. A bubble bursting can produce a bear market, but the two terms are not interchangeable: a bear market describes a large decline, while a bubble describes the speculative conditions that preceded one.'],
        ['How should you use the site’s bubble indicator over time?', 'Use the site’s bubble indicator as a risk dashboard, not a forecast of how many days remain before a market peak. The most useful information is whether several measures are elevated together, how quickly they are changing, and whether the pattern persists.\n\nStart with the [live bubble indicators](https://www.areweinabubbleyet.com/) and compare the current reading with earlier observations. If you are monitoring risk regularly, record a monthly snapshot rather than reacting to every daily market move.\n\nFocus on three questions:\n\n1. **Is the signal broad?** A valuation warning is more significant when leverage, speculation, and market behavior also look stretched.\n2. **Is risk rising or merely high?** A stable elevated reading can persist, while rapid deterioration may show that the market is entering a more fragile phase.\n3. **What would invalidate the concern?** Earnings growth, lower prices, reduced leverage, or improved breadth can ease risk without a crash.\n\nThe methodology page explains [how the bubble indicator works](https://www.areweinabubbleyet.com/learn/how-our-bubble-indicator-works/) and should be read before interpreting changes. Because historical bubbles do not follow a fixed schedule, the indicator is best suited to tracking conditions and informing risk management—not calling the exact top.'],
        ['What are the key takeaways about bubble duration and market peaks?', 'The duration of a stock market bubble can be estimated only after choosing a starting rule, while its precise peak cannot be known in advance. Historical timelines are most useful for showing how long elevated risk can persist and how quickly conditions can reverse.\n\n- Major historical run-ups have lasted from months to several years.\n- The final speculative acceleration is often shorter than the wider bull market.\n- An early warning can remain valid even if prices continue rising for years.\n- Valuation, leverage, issuance, breadth, and liquidity are more informative as a group.\n- A burst may begin suddenly, but the complete decline can take years.\n- The bubble indicator should be read as a changing risk signal, not a market-timing promise.\n\nThe central distinction is between identifying fragility and predicting a catalyst. History can help investors recognize a vulnerable market, but it does not provide a fixed timetable for when stock market bubbles burst.'],
      ],
    },
    es: {
      kicker: '',
      title: '¿Cuánto duran las burbujas del mercado bursátil?',
      description: 'Compara la duración de las principales burbujas bursátiles, por qué las advertencias llegan pronto y qué señales pueden indicar que un auge especulativo se acerca a su máximo.',
      intro: 'Compara la duración de las principales burbujas bursátiles, por qué las advertencias llegan pronto y qué señales pueden indicar que un auge especulativo se acerca a su máximo.',
      sections: [
        ['¿Qué se considera una burbuja bursátil y cuándo comienza?', 'Una burbuja bursátil comienza cuando los precios se desvinculan cada vez más de unos fundamentos plausibles y se mantienen principalmente por las expectativas de nuevas subidas. No existe una fecha oficial de inicio, por lo que las cronologías de las burbujas dependen de si el punto de partida es el mercado alcista general, la ruptura con los fundamentos o el último repunte especulativo.\n\nEl economista Joseph Stiglitz ofreció una definición ampliamente utilizada en un artículo de 1990 publicado en *Journal of Economic Perspectives*: existe una burbuja cuando un precio elevado está impulsado por la creencia de los inversores de que pueden vender a un precio aún más alto, y no por factores que justifiquen el precio en sí.\n\nEsa definición explica por qué es más fácil fechar las burbujas después de que estallan. Los beneficios pueden mejorar, los tipos de interés pueden bajar y las nuevas tecnologías pueden respaldar precios más altos por razones legítimas antes de que la especulación tome el control. Por ello, los analistas pueden coincidir en el máximo y, al mismo tiempo, elegir puntos de partida muy diferentes.\n\nUna cronología práctica debería identificar explícitamente su criterio. Entre los posibles marcadores de inicio se incluyen:\n\n- El comienzo del mercado alcista que finalmente produjo la burbuja.\n- El momento en que las valoraciones se alejaron ampliamente de su rango histórico.\n- El inicio de una rápida aceleración de los precios o de una participación especulativa generalizada.\n- Un cambio reconocible en el apalancamiento, las emisiones, la actividad de negociación o el comportamiento de los inversores.\n\nEstos marcadores forman parte de un marco más amplio para [detectar una burbuja bursátil](https://www.areweinabubbleyet.com/learn/how-to-spot-a-stock-market-bubble/), pero ninguno puede establecer por sí solo una fecha de inicio universalmente aceptada.'],
        ['¿Cuánto duraron históricamente las principales burbujas bursátiles?', 'Las burbujas bursátiles históricas han durado desde varios meses hasta aproximadamente ocho años, dependiendo del episodio y del punto de partida utilizado. Sus fases finales más especulativas normalmente fueron mucho más cortas que los mercados alcistas que las precedieron.\n\nLa siguiente cronología de burbujas bursátiles utiliza un periodo de referencia claramente indicado para cada episodio, en lugar de asumir que cada día de la subida fue necesariamente una burbuja.\n\n| Episodio | Cronología utilizada | Duración aproximada hasta el máximo | Lo que muestra el registro histórico |\n|---|---|---:|---|\n| Burbuja de los Mares del Sur | De enero a agosto de 1720 | 7 meses | El relato histórico del Banco de Inglaterra señala que las acciones de South Sea Company subieron de aproximadamente £128 en enero a cerca de £1.000 en agosto, y luego cayeron hasta unos £124 en diciembre. Fue una manía centrada en una empresa, no una burbuja moderna de un índice de mercado amplio. |\n| Mercado estadounidense de la década de 1920 | De agosto de 1921 a septiembre de 1929 | 8 años | Federal Reserve History informa de que el Dow Jones Industrial Average se multiplicó por seis, pasando de 63 en agosto de 1921 a 381 en septiembre de 1929. Todo el periodo fue un mercado alcista; la fase claramente especulativa llegó más tarde. |\n| Burbuja de activos japonesa | De 1985 a diciembre de 1989 | Aproximadamente 4 años | El Fondo Monetario Internacional ha señalado que los precios de las acciones japonesas aproximadamente se triplicaron entre 1985 y 1989. Los datos históricos del Nikkei sitúan el cierre récord del índice en 38.915,87 el 29 de diciembre de 1989. |\n| Burbuja puntocom | De enero de 1995 a marzo de 2000 | Aproximadamente 5 años | Los datos del Nasdaq publicados a través del Banco de la Reserva Federal de San Luis muestran que el Composite subió de aproximadamente 752 a comienzos de 1995 a 5.048,62 el 10 de marzo de 2000. |\n| Auge de la renta variable china | De mediados de 2014 a mediados de junio de 2015 | Aproximadamente 1 año | El Banco de Pagos Internacionales informó de que los precios de las acciones chinas ganaron aproximadamente un 125% desde mediados de 2014 hasta su máximo de 2015, con la negociación apalancada ayudando a amplificar la subida. |\n\nEstos casos no deberían promediarse para obtener una duración típica de una burbuja. Implicaron estructuras de mercado, condiciones monetarias, métodos de valoración y niveles de apalancamiento diferentes. La comparación muestra, en cambio, que los precios elevados pueden persistir durante años, mientras que el impulso final hacia el mercado puede durar solo meses.'],
        ['¿Por qué pueden seguir creciendo las burbujas después de que aparezcan señales de advertencia?', 'Las burbujas pueden continuar porque una señal de advertencia identifica una vulnerabilidad, no el acontecimiento que obligará a los inversores a vender. Los precios pueden seguir subiendo mientras la liquidez siga siendo abundante, las narrativas sobre los beneficios sigan siendo creíbles y los compradores esperen salir antes que los demás.\n\nEl periodo de las puntocom ofrece un ejemplo claro. El presidente de la Reserva Federal, Alan Greenspan, advirtió sobre la *exuberancia irracional* el 5 de diciembre de 1996, pero los datos del Nasdaq muestran que posteriormente el Composite subió de alrededor de 1.300 a más de 5.000 antes de alcanzar su máximo en marzo de 2000. Una advertencia destacada sobre las valoraciones llegó más de tres años antes del máximo.\n\nVarios factores pueden prolongar la subida:\n\n- **El impulso atrae a nuevos compradores.** Los fuertes rendimientos recientes pueden interpretarse como una confirmación de que las previsiones optimistas son correctas.\n- **Los fundamentos pueden mejorar inicialmente.** La innovación genuina, el crecimiento de los ingresos o la caída de los tipos de interés pueden respaldar parte del avance, incluso cuando posteriormente los precios se exceden.\n- **Los vendedores en corto afrontan un riesgo de sincronización.** Un valor puede estar cada vez más sobrevalorado antes de caer, lo que genera pérdidas potencialmente grandes para los inversores que apuestan contra él.\n- **La presión de los índices de referencia fomenta la participación.** Los gestores profesionales que evitan un sector que sube rápidamente pueden quedar rezagados antes de que estalle la burbuja.\n- **El crédito amplía el poder adquisitivo.** El dinero prestado permite que la demanda crezca más rápido que los recursos líquidos de los inversores.\n\nPor eso, las métricas de valoración no deberían utilizarse como relojes de cuenta atrás. Pueden indicar que los rendimientos esperados a largo plazo son menos atractivos o que el mercado es vulnerable, pero no pueden especificar la fecha del máximo.'],
        ['¿Qué señales de advertencia sugieren que una burbuja puede acercarse a su final?', 'Una burbuja puede acercarse a su final cuando una valoración extrema se combina con precios acelerados, un apalancamiento creciente, emisiones especulativas, un deterioro de la amplitud del mercado y condiciones financieras más restrictivas. Ninguna señal por sí sola identifica de forma fiable el máximo exacto, pero varias señales que se deterioran simultáneamente merecen más atención que un único ratio elevado.\n\nEntre las señales importantes de la fase final se incluyen:\n\n- **Subidas de precios casi verticales.** Una aceleración pronunciada puede indicar que las expectativas y el impulso, más que las nuevas noticias fundamentales, están impulsando los rendimientos.\n- **Los precios se adelantan a los resultados empresariales.** Las valoraciones se vuelven más frágiles cuando los precios de las acciones suben mucho más rápido que las ventas, los beneficios o el flujo de caja en una parte amplia del mercado.\n- **Crecimiento rápido de la inversión financiada con deuda.** El apalancamiento puede amplificar las ganancias durante la subida y provocar ventas forzadas cuando los precios caen. La guía del sitio sobre [la deuda de margen y las burbujas bursátiles](https://www.areweinabubbleyet.com/learn/margin-debt-and-stock-market-bubbles/) explica por qué la dirección y la velocidad del cambio pueden ser más importantes que un único nivel de deuda.\n- **Aumento de las ofertas especulativas.** La investigación de Jay Ritter sobre las OPV en la Universidad de Florida registra una rentabilidad media del 71,7% el primer día para las OPV estadounidenses en 1999, lo que ilustra la intensa demanda de empresas recién cotizadas cerca del máximo de la burbuja puntocom.\n- **Participación cada vez más estrecha.** Un índice puede seguir subiendo aunque participen menos acciones, dejando el rendimiento en manos de un pequeño número de líderes del mercado.\n- **Liquidez más restrictiva.** Los registros de la Reserva Federal muestran que el objetivo de los fondos federales subió del 4,75% antes de junio de 1999 al 6,5% en mayo de 2000. El Nasdaq alcanzó su máximo durante ese ciclo de endurecimiento, aunque las subidas de tipos por sí solas no determinaron el máximo.\n- **Incapacidad de reaccionar ante las buenas noticias.** Cuando los anuncios optimistas ya no producen ganancias duraderas, puede ser una señal de que los compradores se están agotando.\n\nLas burbujas bursátiles estallan cuando suficientes inversores revisan sus expectativas al mismo tiempo y desaparece la demanda marginal. El detonante puede ser unos beneficios decepcionantes, un crédito más restrictivo, una regulación, un fraude o ningún acontecimiento identificable concreto; lo importante es que la confianza y la financiación disponible ya no sostengan el precio vigente.'],
        ['¿Qué suele ocurrir cuando estalla una burbuja bursátil?', 'Cuando estalla una burbuja, los precios suelen caer más rápido de lo que subieron durante la primera parte del auge, pero el descenso completo puede desarrollarse mediante varias caídas y repuntes temporales. El tiempo de recuperación varía entre meses y décadas y a menudo es mucho más largo que la venta inicial.\n\nLa caída de las puntocom del Nasdaq demuestra la diferencia entre la primera ruptura y el desinflamiento completo. Los datos del Banco de la Reserva Federal de San Luis muestran que el Composite cayó de 5.048,62 el 10 de marzo de 2000 a 1.114,11 el 9 de octubre de 2002: una caída de aproximadamente el 78% en 31 meses.\n\nEl episodio de 1929 fue igualmente prolongado. Federal Reserve History registra un máximo del Dow de 381 en septiembre de 1929, mientras que S&P Dow Jones Indices sitúa el mínimo posterior en 41,22 en julio de 1932, aproximadamente un 89% por debajo del máximo.\n\nJapón ilustra cuánto puede tardar la recuperación. Después de cerrar en 38.915,87 en diciembre de 1989, el Nikkei 225 no superó ese récord nominal de cierre hasta febrero de 2024, según los registros del índice Nikkei.\n\nUn desinflamiento típico puede incluir una ruptura brusca, ventas forzadas por parte de inversores apalancados, un rebote que parece marcar el suelo y nuevas caídas a medida que se ajustan las previsiones de beneficios. El estallido de una burbuja puede producir un mercado bajista, pero ambos términos no son intercambiables: un mercado bajista describe una gran caída, mientras que una burbuja describe las condiciones especulativas que la precedieron.'],
        ['¿Cómo debería utilizar el indicador de burbujas del sitio a lo largo del tiempo?', 'Utiliza el indicador de burbujas del sitio como un panel de riesgo, no como una previsión de cuántos días faltan para el máximo del mercado. La información más útil es saber si varias medidas están elevadas al mismo tiempo, con qué rapidez cambian y si el patrón persiste.\n\nComienza con los [indicadores de burbujas en tiempo real](https://www.areweinabubbleyet.com/) y compara la lectura actual con observaciones anteriores. Si supervisas el riesgo con regularidad, registra una observación mensual en lugar de reaccionar a cada movimiento diario del mercado.\n\nConcéntrate en tres preguntas:\n\n1. **¿Es amplia la señal?** Una advertencia de valoración es más significativa cuando el apalancamiento, la especulación y el comportamiento del mercado también parecen excesivos.\n2. **¿Está aumentando el riesgo o simplemente se mantiene alto?** Una lectura elevada estable puede persistir, mientras que un deterioro rápido puede mostrar que el mercado está entrando en una fase más frágil.\n3. **¿Qué invalidaría la preocupación?** El crecimiento de los beneficios, unos precios más bajos, un menor apalancamiento o una mejor amplitud pueden aliviar el riesgo sin que se produzca un desplome.\n\nLa página sobre la metodología explica [cómo funciona el indicador de burbujas](https://www.areweinabubbleyet.com/learn/how-our-bubble-indicator-works/) y debería leerse antes de interpretar los cambios. Como las burbujas históricas no siguen un calendario fijo, el indicador es más adecuado para seguir las condiciones e informar la gestión del riesgo, no para determinar el máximo exacto.'],
        ['¿Cuáles son las conclusiones clave sobre la duración de las burbujas y los máximos del mercado?', 'La duración de una burbuja bursátil solo puede estimarse después de elegir un criterio de inicio, mientras que su máximo exacto no puede conocerse de antemano. Las cronologías históricas son más útiles para mostrar cuánto tiempo puede persistir un riesgo elevado y con qué rapidez pueden revertirse las condiciones.\n\n- Las principales subidas históricas han durado desde meses hasta varios años.\n- La aceleración especulativa final suele ser más corta que el mercado alcista general.\n- Una advertencia temprana puede seguir siendo válida aunque los precios continúen subiendo durante años.\n- La valoración, el apalancamiento, las emisiones, la amplitud y la liquidez son más informativos en conjunto.\n- Un estallido puede comenzar de repente, pero la caída completa puede tardar años.\n- El indicador de burbujas debe interpretarse como una señal de riesgo cambiante, no como una promesa de sincronización del mercado.\n\nLa distinción central está entre identificar la fragilidad y predecir un detonante. La historia puede ayudar a los inversores a reconocer un mercado vulnerable, pero no proporciona un calendario fijo para saber cuándo estallan las burbujas bursátiles.'],
      ],
    },
  },
] as const;

export function articlePath(article: typeof articles[number], locale: Locale) {
  return locale === 'es' ? `/es/aprender/${article.slug.es}/` : `/learn/${article.slug.en}/`;
}

export function articleAlternatePath(article: typeof articles[number], locale: ArticleLocale) {
  return articlePath(article, locale === 'en' ? 'es' : 'en');
}
