import type { Locale } from './i18n';
export type ArticleLocale = 'en' | 'es';

export const articles = [
  {
    id: 'spot-bubble',
    slug: { en: 'how-to-spot-a-stock-market-bubble', es: 'como-detectar-una-burbuja-bursatil' },
    en: {
      kicker: 'BUBBLE BASICS', title: 'How to spot a stock market bubble',
      description: 'Learn the clearest signs of a stock market bubble, from stretched valuations and leverage to investor positioning, credit and complacency.',
      intro: 'Bubbles rarely announce themselves with one perfect number. They emerge when expensive prices, easy financing and confident behavior begin reinforcing one another.',
      sections: [
        ['Start with valuation, not headlines', 'High prices alone do not prove a bubble. Compare prices with durable earning power and the size of the economy. Shiller CAPE and market value to GDP are slow-moving gauges that reveal when optimism has become historically expensive.'],
        ['Look for fuel', 'Leverage turns enthusiasm into fragility. Fast-rising margin debt means more investors are borrowing against securities, which can amplify gains on the way up and forced selling on the way down.'],
        ['Demand confirmation', 'Positioning, credit spreads and volatility show whether investors and lenders are behaving as if risk has disappeared. A convincing bubble signal is broad: several independent gauges should be hot at the same time.']
      ]
    },
    es: {
      kicker: 'CONCEPTOS BÁSICOS', title: 'Cómo detectar una burbuja bursátil',
      description: 'Aprende las señales más claras de una burbuja bursátil: valoración, apalancamiento, posicionamiento, crédito y complacencia.',
      intro: 'Las burbujas casi nunca se anuncian con un único número perfecto. Aparecen cuando los precios caros, la financiación fácil y la confianza se refuerzan mutuamente.',
      sections: [
        ['Empieza por la valoración, no por los titulares', 'Los precios altos por sí solos no demuestran una burbuja. Compáralos con los beneficios sostenibles y el tamaño de la economía. El CAPE de Shiller y el valor de mercado frente al PIB muestran cuándo el optimismo se ha vuelto históricamente caro.'],
        ['Busca el combustible', 'El apalancamiento convierte el entusiasmo en fragilidad. Un crecimiento rápido de la deuda de margen implica más dinero prestado contra valores, lo que amplifica las subidas y las ventas forzadas durante una caída.'],
        ['Exige confirmación', 'El posicionamiento, los diferenciales de crédito y la volatilidad indican si inversores y prestamistas actúan como si el riesgo hubiera desaparecido. Una señal convincente debe ser amplia: varios indicadores independientes tienen que calentarse a la vez.']
      ]
    }
  },
  {
    id: 'cape',
    slug: { en: 'what-is-the-shiller-cape-ratio', es: 'que-es-el-ratio-cape-de-shiller' },
    en: {
      kicker: 'VALUATION GUIDE', title: 'What is the Shiller CAPE ratio?',
      description: 'A plain-English guide to the Shiller CAPE ratio, what it measures, its historical bubble signals and the limits investors should understand.',
      intro: 'The Shiller CAPE asks a deliberately patient question: how much are investors paying for a decade of inflation-adjusted corporate earnings?',
      sections: [
        ['Why use ten years of earnings?', 'One year of profits can be distorted by a recession, a boom or an unusual shock. Averaging ten inflation-adjusted years smooths the cycle and makes comparisons across market eras more useful.'],
        ['What counts as expensive?', 'There is no magic cutoff, but readings above 30 have historically belonged to a rare and expensive part of the distribution. The dot-com peak was much higher; other costly markets corrected without matching it.'],
        ['What CAPE cannot tell you', 'CAPE is poor at timing. An expensive market can become more expensive and remain there for years. Use it as a pressure gauge, then look to leverage, positioning, credit and sentiment for confirmation.']
      ]
    },
    es: {
      kicker: 'GUÍA DE VALORACIÓN', title: '¿Qué es el ratio CAPE de Shiller?',
      description: 'Guía clara sobre el CAPE de Shiller: qué mide, sus señales históricas de burbuja y los límites que todo inversor debe conocer.',
      intro: 'El CAPE de Shiller plantea una pregunta deliberadamente paciente: ¿cuánto pagan los inversores por una década de beneficios empresariales ajustados por inflación?',
      sections: [
        ['¿Por qué usar diez años de beneficios?', 'Un solo año puede estar distorsionado por una recesión, un auge o un choque excepcional. La media de diez años ajustados por inflación suaviza el ciclo y permite comparar épocas distintas.'],
        ['¿Qué se considera caro?', 'No existe un umbral mágico, pero las lecturas superiores a 30 han ocupado históricamente una zona rara y cara. El máximo puntocom fue mucho mayor; otros mercados costosos corrigieron sin alcanzarlo.'],
        ['Lo que el CAPE no puede decir', 'El CAPE no sirve para anticipar fechas. Un mercado caro puede encarecerse y seguir así durante años. Úsalo como indicador de presión y busca confirmación en el apalancamiento, el posicionamiento, el crédito y el sentimiento.']
      ]
    }
  },
  {
    id: 'margin-debt',
    slug: { en: 'margin-debt-and-stock-market-bubbles', es: 'deuda-de-margen-y-burbujas-bursatiles' },
    en: {
      kicker: 'LEVERAGE GUIDE', title: 'Margin debt and stock market bubbles',
      description: 'Understand how FINRA margin debt can amplify stock market bubbles, why its rate of change matters and what the indicator cannot predict.',
      intro: 'Margin debt is money investors borrow against securities in their brokerage accounts. It is both a measure of confidence and a source of forced selling.',
      sections: [
        ['Why acceleration matters', 'The dollar level naturally grows with the market and the economy, so the pace of change is often more informative. Rapid year-over-year growth suggests that risk-taking is accelerating rather than merely keeping up.'],
        ['The feedback loop', 'Borrowing can lift demand and prices, which increases collateral values and enables more borrowing. When prices fall, the loop can reverse through margin calls and compulsory sales.'],
        ['Read it beside valuation', 'Margin debt is not a standalone sell signal. Rising leverage is most concerning when valuations are already stretched and lenders and investors remain unusually relaxed about risk.']
      ]
    },
    es: {
      kicker: 'GUÍA DE APALANCAMIENTO', title: 'Deuda de margen y burbujas bursátiles',
      description: 'Entiende cómo la deuda de margen de FINRA puede amplificar una burbuja, por qué importa su crecimiento y qué no puede predecir.',
      intro: 'La deuda de margen es el dinero que los inversores piden prestado contra los valores de sus cuentas. Mide confianza y también puede provocar ventas forzadas.',
      sections: [
        ['Por qué importa la aceleración', 'El nivel en dólares crece de forma natural con el mercado y la economía, por lo que el ritmo de cambio suele ser más informativo. Un aumento interanual rápido indica que la toma de riesgo se acelera.'],
        ['El círculo de retroalimentación', 'El crédito puede elevar la demanda y los precios, aumentando el valor del colateral y permitiendo pedir aún más prestado. Cuando los precios caen, el círculo se invierte mediante llamadas de margen y ventas obligatorias.'],
        ['Léela junto a la valoración', 'La deuda de margen no es una señal de venta independiente. El apalancamiento preocupa más cuando la valoración ya está tensionada y prestamistas e inversores siguen demasiado tranquilos ante el riesgo.']
      ]
    }
  },
  {
    id: 'methodology',
    slug: { en: 'how-our-bubble-indicator-works', es: 'como-funciona-el-indicador-de-burbuja' },
    en: {
      kicker: 'METHODOLOGY', title: 'How our bubble indicator works',
      description: 'See how our stock market bubble indicator combines six signals, why valuation and leverage come first, and what each weight contributes.',
      intro: 'The indicator is a structured argument, not a forecast. It asks whether expensive prices, leverage and confident risk-taking are appearing together—and makes every judgment visible.',
      sections: [
        ['From six readings to one score', 'Each signal is clamped to a 0–100 pressure score using a fixed range: CAPE 18–42, market value to GDP 80–240%, margin-debt growth −10–40%, household equity allocation 25–50%, credit spreads 4.5–1.5% and VIX 30–10. The last two run in reverse because lower readings imply more complacency. We multiply those scores by their weights and add them. The composite becomes NO below 30, NOT YET at 30, MAYBE at 45, PROBABLY at 60 and YES at 75.'],
        ['First priority: valuation · 45%', 'Valuation gets the largest share because detachment from economic fundamentals is the defining ingredient of a bubble. Shiller CAPE receives 25% and market value to GDP 20%. CAPE compares prices with smoothed earning power; market value to GDP compares the whole market with the economy supporting it. Using both keeps one valuation lens from deciding the verdict alone.'],
        ['Second priority: leverage · 25%', 'Margin debt receives 25%, equal to the largest single valuation signal. Borrowing does more than accompany optimism: it can amplify demand on the way up and force selling when collateral falls. We score its year-over-year growth rather than its dollar level, because the level naturally rises as markets and the economy grow.'],
        ['Confirmation signals · 30%', 'The remaining signals test whether the enthusiasm is broad. Credit spreads receive 12% because lenders provide an independent market price for risk. Household equity allocation receives 10% because crowded ownership leaves less uncommitted buying power. The VIX receives 8%, the smallest weight, because short-term calm can be useful confirmation but is noisy and can reverse quickly.'],
        ['Why the weights are not probabilities', 'The weights express priority, not the chance of a crash: 25% does not mean a signal predicts one quarter of market outcomes. Slow-moving fundamentals and leverage carry 70% so a fleeting mood cannot dominate the result. A separate confidence measure checks how closely the six signals agree and how far the composite sits from the next decision boundary. Read the score as a transparent temperature check, never as a market-timing rule.']
      ]
    },
    es: {
      kicker: 'METODOLOGÍA', title: 'Cómo funciona el indicador de burbuja',
      description: 'Descubre cómo nuestro indicador de burbuja bursátil combina seis señales, por qué prioriza valoración y apalancamiento y qué aporta cada peso.',
      intro: 'El indicador es un argumento estructurado, no una predicción. Pregunta si los precios caros, el apalancamiento y la confianza ante el riesgo aparecen a la vez, y deja cada decisión a la vista.',
      sections: [
        ['De seis lecturas a una puntuación', 'Cada señal se limita a una puntuación de presión de 0 a 100 con un rango fijo: CAPE 18–42, valor de mercado/PIB 80–240%, crecimiento de la deuda de margen −10–40%, asignación familiar a bolsa 25–50%, diferenciales de crédito 4,5–1,5% y VIX 30–10. Los dos últimos se invierten porque una lectura menor implica más complacencia. Multiplicamos las puntuaciones por sus pesos y las sumamos. El índice dice NO por debajo de 30, TODAVÍA NO desde 30, QUIZÁ desde 45, PROBABLEMENTE desde 60 y SÍ desde 75.'],
        ['Primera prioridad: valoración · 45%', 'La valoración recibe el mayor peso porque la separación respecto a los fundamentos económicos es el ingrediente esencial de una burbuja. El CAPE de Shiller aporta un 25% y el valor de mercado frente al PIB un 20%. El CAPE compara precios con beneficios suavizados; el segundo compara todo el mercado con la economía que lo sostiene. Usar ambos evita que una sola perspectiva decida el resultado.'],
        ['Segunda prioridad: apalancamiento · 25%', 'La deuda de margen aporta un 25%, igual que la mayor señal de valoración. El crédito no solo acompaña al optimismo: puede amplificar la demanda durante la subida y forzar ventas cuando cae el valor del colateral. Medimos su crecimiento interanual, no el nivel en dólares, porque ese nivel aumenta de forma natural con el mercado y la economía.'],
        ['Señales de confirmación · 30%', 'Las señales restantes comprueban si el entusiasmo es amplio. Los diferenciales de crédito pesan un 12% porque los prestamistas aportan un precio del riesgo independiente. La asignación familiar a bolsa pesa un 10% porque un posicionamiento saturado deja menos compradores disponibles. El VIX pesa un 8%, el mínimo, porque la calma a corto plazo confirma el contexto, pero es ruidosa y puede cambiar rápido.'],
        ['Los pesos no son probabilidades', 'Los pesos expresan prioridad, no la probabilidad de una caída: un 25% no significa que una señal explique la cuarta parte de los resultados del mercado. Los fundamentales lentos y el apalancamiento suman un 70% para que un cambio fugaz de ánimo no domine el índice. Una medida de confianza separada evalúa cuánto coinciden las seis señales y a qué distancia está el resultado del siguiente umbral. Léelo como un termómetro transparente, nunca como una regla para anticipar el mercado.']
      ]
    }
  },
  {
    id: 'stock-market-bubble-vs-bear-market',
    slug: {
      en: 'stock-market-bubble-vs-bear-market',
      es: 'stock-market-bubble-vs-bear-market-how-to-tell-the-difference',
    },
    en: {
      kicker: '',
      title: 'Stock Market Bubble vs. Bear Market: How to Tell the Difference',
      description: 'Compare bubbles and bear markets using valuation, behavior, fundamentals, breadth, margin debt, and history—without relying on one signal.',
      intro: '',
      sections: [
        ['What is the difference between a stock market bubble and a bear market?', 'A stock market bubble is a period when prices appear unjustifiably high because investors expect them to keep rising, while a bear market is a substantial decline from a recent peak. A bubble describes valuation and behavior; a bear market describes price direction.\n\nEconomist Joseph Stiglitz offered a useful definition in a 1990 *Journal of Economic Perspectives* paper: a bubble exists when today\'s high price depends on investors believing tomorrow\'s selling price will be higher, even though fundamentals do not justify it.\n\nA bear market is easier to identify. The U.S. Securities and Exchange Commission\'s Investor.gov describes it as a prolonged decline, typically involving a drop of at least 20% from recent highs amid widespread pessimism. The 20% threshold is a market convention, not an economic law.\n\nThis distinction matters because a bubble can keep inflating while the market is rising. A bear market becomes visible only after prices have already fallen. A bursting bubble can cause a bear market, but the two conditions are not interchangeable.'],
        ['How do valuation, investor behavior, fundamentals, and breadth differ?', 'Bubble evidence usually appears in unusually demanding valuations, speculative behavior, weak links between prices and fundamentals, and sometimes narrow participation. Bear-market evidence is primarily a large price decline, regardless of what valuations or investor behavior looked like beforehand.\n\n| Feature | Stock market bubble | Bear market |\n|---|---|---|\n| Valuation | Prices appear extreme relative to earnings, cash flows or other anchors | Valuations may begin high, normal or even low |\n| Investor behavior | Enthusiasm, fear of missing out and confidence that recent gains will continue | Pessimism, risk reduction and demand for liquidity become more common |\n| Fundamentals | Prices may outrun realistic expectations for profits or economic growth | Falling earnings, recession risk or higher interest rates may justify part of the decline |\n| Market breadth | Speculation may be broad or concentrated in a popular sector | A broad index must fall substantially, although individual industries can behave differently |\n| Timing | Diagnosed before or after a peak, with considerable uncertainty | Confirmed after a decline crosses the chosen threshold |\n\nMarket breadth means the proportion of securities participating in a move. Analysts may examine advance-decline lines or the percentage of stocks above long-term moving averages. An index rising because of a small group of large companies can conceal weakness underneath, but narrow breadth alone does not prove a bubble.\n\nThe bubble market vs. bear market distinction is therefore partly about sequence: speculative excess may occur first, while the bear market is one possible outcome later.'],
        ['Why can a bear market happen without a preceding bubble?', 'A bear market can result from an economic shock, recession, earnings contraction, tighter monetary policy or liquidity crisis even when investors were not displaying classic bubble behavior. Prices do not have to be irrationally high before they fall 20%.\n\nCommon non-bubble causes include:\n\n- A rapid increase in interest rates, which reduces the present value of future cash flows.\n- An unexpected recession that lowers expected corporate earnings.\n- A war, pandemic or energy shock that changes the economic outlook.\n- Forced selling or a liquidity shortage that temporarily overwhelms buyers.\n- A normal repricing after investors learn that previous assumptions were too optimistic but not wildly speculative.\n\nThe Federal Reserve\'s *Financial Stability Report* treats elevated asset valuations as a vulnerability rather than a stand-alone trigger. A shock and the financial system\'s capacity to absorb it also affect whether falling prices become disruptive.'],
        ['What warning signs suggest that a stock market bubble may be forming?', 'The strongest warning comes from several independent signs appearing together, not from one ratio crossing a fixed threshold. Investors should look for a combination of stretched prices, speculative behavior, leverage and weakening market structure.\n\nPractical stock market bubble warning signs include:\n\n1. **Valuations far above their own history.** Price-to-earnings, price-to-sales and cyclically adjusted measures become more concerning when several tell the same story.\n2. **Prices separating from business results.** Share prices may accelerate while earnings, revenue or cash-flow expectations improve much more slowly.\n3. **Speculation based mainly on resale.** Buyers focus on finding someone who will pay more rather than estimating the asset\'s future cash flows.\n4. **Rapid growth in leverage.** Borrowed money can magnify gains during the rise and force sales when prices turn.\n5. **Indiscriminate demand.** Investors may treat low-quality and high-quality companies similarly or dismiss traditional risks as obsolete.\n6. **Narrowing participation.** Major indexes can keep setting records even as fewer constituent stocks participate.\n7. **A persuasive new-era narrative.** Technological or economic change may be real, but investors can still overpay for it.\n\nCharles Kindleberger and Robert Aliber\'s *Manias, Panics, and Crashes* documents the recurring role of credit expansion, compelling narratives and momentum in historical speculative episodes. These patterns are useful context, not a mechanical countdown to a crash. For a broader checklist, see [how to spot a stock market bubble](https://www.areweinabubbleyet.com/learn/how-to-spot-a-stock-market-bubble/).'],
        ['How should valuation measures, margin debt, and the site’s bubble indicator be used together?', 'Valuation, leverage and a composite indicator answer different questions, so they are more informative together than separately. None can reliably identify the exact market top or date of a decline.\n\n### Valuation measures\n\nThe Shiller CAPE compares the market\'s inflation-adjusted price with average inflation-adjusted earnings over the previous 10 years. Data maintained by Robert Shiller at Yale University make it possible to compare current readings with a long history, while research by John Campbell and Shiller has associated high valuation ratios with lower long-horizon returns rather than precise short-term crash timing.\n\nAn elevated CAPE may reflect expensive prices, unusually depressed past earnings, low interest rates or expectations of durable growth. It should be compared with other valuation measures and the economic environment. The site\'s guide to the [Shiller CAPE ratio](https://www.areweinabubbleyet.com/learn/what-is-the-shiller-cape-ratio/) explains those limitations in more detail.\n\n### Margin debt\n\nFINRA publishes monthly statistics for debit balances in customers\' securities margin accounts. A rapid rise can indicate greater willingness to speculate with borrowed money, but the nominal total also tends to grow with market size and does not capture every form of leverage, including all derivatives or institutional borrowing.\n\nMargin debt is most concerning when it rises quickly alongside expensive valuations and exuberant behavior. Its role and limitations are covered in the site\'s analysis of [margin debt and stock market bubbles](https://www.areweinabubbleyet.com/learn/margin-debt-and-stock-market-bubbles/).\n\n### The site’s bubble indicator\n\nA composite score can organize multiple signals and reduce the temptation to make a decision from one dramatic chart. Readers should still inspect the date, underlying inputs and methodology rather than treating the score as a prediction; the construction and limits are described in [how our bubble indicator works](https://www.areweinabubbleyet.com/learn/how-our-bubble-indicator-works/).'],
        ['Which historical examples show the difference between bubbles and ordinary bear markets?', 'The dot-com collapse combined strong bubble evidence with a later bear market, whereas the 2020 decline was primarily a sudden external shock. The 2022 bear market was a mixed case in which macroeconomic repricing and speculative excess in some segments occurred together.\n\n### The dot-com bubble and subsequent bear market\n\nThe Nasdaq Composite closed at 5,048.62 on March 10, 2000, and 1,114.11 on October 9, 2002, a decline of about 78%, based on the Federal Reserve Bank of St. Louis FRED series. The large fall established the bear market, while the earlier combination of extraordinary expectations, speculation and valuations supports the separate bubble diagnosis.\n\n### The pandemic bear market of 2020\n\nThe S&P 500 fell from 3,386.15 on February 19, 2020, to 2,237.40 on March 23, a decline of approximately 34%, according to FRED data. The National Bureau of Economic Research determined that a recession began in February and ended in April as the pandemic and public-health restrictions abruptly interrupted economic activity.\n\nThat episode shows why a fast bear market does not, by itself, prove that a bubble burst. An external shock can change expected profits and risk tolerance almost overnight.\n\n### The inflation and rate-driven bear market of 2022\n\nThe S&P 500 declined about 25% from January 3 to October 12, 2022, based on FRED closing values. The Bureau of Labor Statistics reported that annual consumer inflation reached 9.1% in June, while Federal Reserve records show seven rate increases during the year, ending with a federal-funds target range of 4.25% to 4.50%.\n\nSome speculative assets experienced bubble-like unwinds, but a broad index decline during rapid monetary tightening does not prove that the entire market had been a bubble. Different sectors can receive different diagnoses at the same time.'],
        ['How can you diagnose current or recent market conditions?', 'First determine whether a broad index is in a confirmed bear market, then separately evaluate whether bubble evidence existed before or during the decline. Keeping those questions separate prevents a large loss from becoming retroactive proof of speculation.\n\nUse this sequence:\n\n1. **Measure the decline.** Has a broad index fallen roughly 20% from a recent closing high? If so, the conventional bear-market label applies.\n2. **Check pre-decline valuations.** Were several valuation measures extreme relative to relevant history?\n3. **Compare prices with fundamentals.** Did earnings and cash-flow expectations plausibly support the previous price level?\n4. **Examine behavior and leverage.** Were investors borrowing aggressively, chasing recent winners or dismissing risk?\n5. **Inspect breadth.** Was enthusiasm widespread, or was the index dependent on a small group of companies?\n6. **Identify the catalyst.** Did the decline follow a speculative reversal, or did a recession, policy shift or external shock change fundamentals?\n\nHigh bubble evidence without a major decline suggests a possible bubble within an ongoing bull market. A 20% decline with little prior evidence of excess is better described as a non-bubble bear market. Strong evidence of both is consistent with a bubble that has begun to burst, although reasonable analysts may still disagree.'],
        ['What should investors conclude from bubble signals?', 'Bubble signals should change assessments of risk and expected return, not create certainty that a crash is imminent. They are inputs for portfolio decisions, not automatic instructions to sell everything.\n\nInvestors should not conclude that every stock is overvalued, that a high indicator can identify the top, or that cash is risk-free after inflation. A bubble can become more extreme before ending, while an expensive market can correct through years of earnings growth rather than a sudden crash.\n\nMore defensible responses include reviewing concentration, rebalancing toward a chosen asset allocation, limiting leverage and checking whether near-term spending needs depend on volatile assets. FINRA notes that diversification can reduce the risk of major losses caused by overemphasis on a single security or asset class, although it cannot prevent all losses.'],
        ['Can a bubble exist during a bull market?', 'Yes. Most bubbles form while prices are rising, so a market can simultaneously meet the definition of a bull market and display strong bubble warning signs.'],
        ['Can a bear market become a bubble?', 'A falling market does not itself turn into a bubble, because the terms describe different conditions. A rebound from a bear market can eventually develop speculative valuations and behavior, creating a new bubble even before every asset recovers its previous high.'],
        ['How long can a stock market bubble last?', 'There is no fixed duration because valuation can remain elevated while earnings grow, financing stays available and investors continue to accept optimistic assumptions. Bubbles are often easiest to identify retrospectively, which is why duration cannot be used as a reliable timing tool.'],
        ['Does a 20% market decline prove that a bubble has burst?', 'No. A 20% decline supports the conventional bear-market label, but proving a bubble requires separate evidence about earlier valuation, fundamentals, leverage and investor behavior.'],
      ],
    },
    es: {
      kicker: '',
      title: 'Burbuja bursátil vs. mercado bajista: cómo distinguirlos',
      description: 'Compara las burbujas y los mercados bajistas mediante la valoración, el comportamiento, los fundamentales, la amplitud del mercado, la deuda de margen y la historia, sin depender de una sola señal.',
      intro: '',
      sections: [
        ['¿Cuál es la diferencia entre una burbuja bursátil y un mercado bajista?', 'Una burbuja bursátil es un periodo en el que los precios parecen injustificadamente altos porque los inversores esperan que sigan subiendo, mientras que un mercado bajista es un descenso sustancial desde un máximo reciente. Una burbuja describe la valoración y el comportamiento; un mercado bajista describe la dirección de los precios.\n\nEl economista Joseph Stiglitz ofreció una definición útil en un artículo de 1990 publicado en el *Journal of Economic Perspectives*: existe una burbuja cuando el precio alto de hoy depende de que los inversores crean que el precio de venta de mañana será más alto, aunque los fundamentales no lo justifiquen.\n\nUn mercado bajista es más fácil de identificar. La Comisión de Bolsa y Valores de Estados Unidos, en Investor.gov, lo describe como un descenso prolongado que normalmente implica una caída de al menos el 20% desde los máximos recientes, en un contexto de pesimismo generalizado. El umbral del 20% es una convención del mercado, no una ley económica.\n\nEsta distinción importa porque una burbuja puede seguir inflándose mientras el mercado sube. Un mercado bajista solo se hace visible después de que los precios ya han caído. El estallido de una burbuja puede provocar un mercado bajista, pero ambas condiciones no son intercambiables.'],
        ['¿En qué se diferencian la valoración, el comportamiento de los inversores, los fundamentales y la amplitud del mercado?', 'Las señales de una burbuja suelen aparecer en valoraciones inusualmente exigentes, comportamiento especulativo, vínculos débiles entre los precios y los fundamentales y, en ocasiones, una participación reducida. La evidencia de un mercado bajista es principalmente una gran caída de los precios, independientemente del aspecto que tuvieran antes las valoraciones o el comportamiento de los inversores.\n\n| Característica | Burbuja bursátil | Mercado bajista |\n|---|---|---|\n| Valoración | Los precios parecen extremos en relación con los beneficios, los flujos de caja u otros puntos de referencia | Las valoraciones pueden comenzar altas, normales o incluso bajas |\n| Comportamiento de los inversores | Entusiasmo, miedo a quedarse fuera y confianza en que las ganancias recientes continuarán | El pesimismo, la reducción del riesgo y la demanda de liquidez se vuelven más habituales |\n| Fundamentales | Los precios pueden superar las expectativas realistas de beneficios o crecimiento económico | La caída de los beneficios, el riesgo de recesión o unos tipos de interés más altos pueden justificar parte del descenso |\n| Amplitud del mercado | La especulación puede ser amplia o concentrarse en un sector popular | Un índice amplio debe caer sustancialmente, aunque las distintas industrias pueden comportarse de forma diferente |\n| Momento | Se diagnostica antes o después de un máximo, con una incertidumbre considerable | Se confirma después de que la caída cruza el umbral elegido |\n\nLa amplitud del mercado se refiere a la proporción de valores que participan en un movimiento. Los analistas pueden examinar las líneas de avances y descensos o el porcentaje de acciones que cotizan por encima de sus medias móviles de largo plazo. Un índice que sube gracias a un pequeño grupo de grandes empresas puede ocultar debilidad subyacente, pero una amplitud reducida por sí sola no demuestra que exista una burbuja.\n\nPor tanto, la distinción entre mercado de burbuja y mercado bajista tiene que ver en parte con la secuencia: el exceso especulativo puede producirse primero, mientras que el mercado bajista es uno de los posibles resultados posteriores.'],
        ['¿Por qué puede producirse un mercado bajista sin una burbuja previa?', 'Un mercado bajista puede ser consecuencia de un shock económico, una recesión, una contracción de los beneficios, una política monetaria más restrictiva o una crisis de liquidez, incluso cuando los inversores no mostraban el comportamiento clásico de una burbuja. Los precios no tienen que ser irracionalmente altos antes de caer un 20%.\n\nEntre las causas habituales no relacionadas con una burbuja se incluyen:\n\n- Un aumento rápido de los tipos de interés, que reduce el valor presente de los flujos de caja futuros.\n- Una recesión inesperada que disminuye los beneficios corporativos previstos.\n- Una guerra, una pandemia o un shock energético que cambia las perspectivas económicas.\n- Ventas forzadas o una escasez de liquidez que supera temporalmente la capacidad de los compradores.\n- Una valoración normal a la baja después de que los inversores descubran que las hipótesis anteriores eran demasiado optimistas, pero no desmesuradamente especulativas.\n\nEl *Financial Stability Report* de la Reserva Federal considera las valoraciones elevadas de los activos una vulnerabilidad, no un detonante independiente. Un shock y la capacidad del sistema financiero para absorberlo también influyen en que la caída de los precios se vuelva disruptiva.'],
        ['¿Qué señales de advertencia sugieren que podría estar formándose una burbuja bursátil?', 'La advertencia más sólida surge cuando aparecen juntas varias señales independientes, no cuando un solo ratio cruza un umbral fijo. Los inversores deberían buscar una combinación de precios excesivamente elevados, comportamiento especulativo, apalancamiento y un debilitamiento de la estructura del mercado.\n\nEntre las señales prácticas de advertencia de una burbuja bursátil se incluyen:\n\n1. **Valoraciones muy por encima de su propio historial.** Los ratios precio-beneficios, precio-ventas y las medidas ajustadas cíclicamente resultan más preocupantes cuando varios cuentan la misma historia.\n2. **Separación entre los precios y los resultados empresariales.** Los precios de las acciones pueden acelerarse mientras las expectativas de beneficios, ingresos o flujos de caja mejoran mucho más lentamente.\n3. **Especulación basada principalmente en la reventa.** Los compradores se centran en encontrar a alguien que pague más, en lugar de estimar los flujos de caja futuros del activo.\n4. **Crecimiento rápido del apalancamiento.** El dinero prestado puede amplificar las ganancias durante la subida y forzar ventas cuando los precios cambian de rumbo.\n5. **Demanda indiscriminada.** Los inversores pueden tratar de forma similar a las empresas de baja y alta calidad, o descartar los riesgos tradicionales por considerarlos obsoletos.\n6. **Participación cada vez más reducida.** Los principales índices pueden seguir marcando récords mientras participan menos acciones integrantes.\n7. **Una narrativa convincente de nueva era.** El cambio tecnológico o económico puede ser real, pero los inversores aun así pueden pagar demasiado por él.\n\nEl libro *Manias, Panics, and Crashes*, de Charles Kindleberger y Robert Aliber, documenta el papel recurrente de la expansión del crédito, las narrativas convincentes y el impulso en episodios especulativos históricos. Estos patrones son un contexto útil, no una cuenta atrás mecánica hacia un desplome. Para consultar una lista más amplia, véase [cómo detectar una burbuja bursátil](https://www.areweinabubbleyet.com/learn/how-to-spot-a-stock-market-bubble/).'],
        ['¿Cómo deben utilizarse conjuntamente las medidas de valoración, la deuda de margen y el indicador de burbuja del sitio?', 'La valoración, el apalancamiento y un indicador compuesto responden a preguntas diferentes, por lo que son más informativos juntos que por separado. Ninguno puede identificar de forma fiable el máximo exacto del mercado ni la fecha de una caída.\n\n### Medidas de valoración\n\nEl CAPE de Shiller compara el precio del mercado ajustado por inflación con los beneficios medios ajustados por inflación de los 10 años anteriores. Los datos mantenidos por Robert Shiller en la Universidad de Yale permiten comparar las lecturas actuales con una larga historia, mientras que las investigaciones de John Campbell y Shiller han asociado los ratios de valoración altos con rendimientos inferiores a largo plazo, no con una predicción precisa del momento de un desplome a corto plazo.\n\nUn CAPE elevado puede reflejar precios caros, beneficios pasados excepcionalmente deprimidos, tipos de interés bajos o expectativas de crecimiento duradero. Debe compararse con otras medidas de valoración y con el entorno económico. La guía del sitio sobre el [ratio CAPE de Shiller](https://www.areweinabubbleyet.com/learn/what-is-the-shiller-cape-ratio/) explica estas limitaciones con más detalle.\n\n### Deuda de margen\n\nFINRA publica estadísticas mensuales sobre los saldos deudores de las cuentas de margen de valores de los clientes. Un aumento rápido puede indicar una mayor disposición a especular con dinero prestado, pero el total nominal también tiende a crecer junto con el tamaño del mercado y no incluye todas las formas de apalancamiento, incluidos todos los derivados o los préstamos institucionales.\n\nLa deuda de margen resulta más preocupante cuando aumenta rápidamente junto con valoraciones caras y un comportamiento eufórico. Su función y sus limitaciones se analizan en el estudio del sitio sobre [la deuda de margen y las burbujas bursátiles](https://www.areweinabubbleyet.com/learn/margin-debt-and-stock-market-bubbles/).\n\n### El indicador de burbuja del sitio\n\nUna puntuación compuesta puede organizar múltiples señales y reducir la tentación de tomar una decisión basándose en un solo gráfico llamativo. Los lectores aún deberían examinar la fecha, los datos subyacentes y la metodología, en lugar de tratar la puntuación como una predicción; la construcción y las limitaciones se describen en [cómo funciona nuestro indicador de burbuja](https://www.areweinabubbleyet.com/learn/how-our-bubble-indicator-works/).'],
        ['¿Qué ejemplos históricos muestran la diferencia entre las burbujas y los mercados bajistas ordinarios?', 'El desplome de las puntocom combinó señales sólidas de una burbuja con un mercado bajista posterior, mientras que la caída de 2020 fue principalmente un shock externo repentino. El mercado bajista de 2022 fue un caso mixto en el que la reevaluación macroeconómica y el exceso especulativo en algunos segmentos se produjeron al mismo tiempo.\n\n### La burbuja de las puntocom y el mercado bajista posterior\n\nEl Nasdaq Composite cerró en 5.048,62 el 10 de marzo de 2000 y en 1.114,11 el 9 de octubre de 2002, un descenso de aproximadamente el 78%, según la serie FRED del Banco de la Reserva Federal de San Luis. La gran caída estableció el mercado bajista, mientras que la combinación anterior de expectativas extraordinarias, especulación y valoraciones respalda el diagnóstico separado de una burbuja.\n\n### El mercado bajista de la pandemia de 2020\n\nEl S&P 500 cayó de 3.386,15 el 19 de febrero de 2020 a 2.237,40 el 23 de marzo, un descenso aproximado del 34%, según los datos de FRED. La Oficina Nacional de Investigación Económica determinó que la recesión comenzó en febrero y terminó en abril, cuando la pandemia y las restricciones de salud pública interrumpieron abruptamente la actividad económica.\n\nEste episodio muestra por qué un mercado bajista rápido no demuestra por sí mismo que haya estallado una burbuja. Un shock externo puede cambiar casi de la noche a la mañana los beneficios previstos y la tolerancia al riesgo.\n\n### El mercado bajista de 2022 provocado por la inflación y los tipos de interés\n\nEl S&P 500 cayó aproximadamente un 25% del 3 de enero al 12 de octubre de 2022, según los valores de cierre de FRED. La Oficina de Estadísticas Laborales informó de que la inflación anual de los consumidores alcanzó el 9,1% en junio, mientras que los registros de la Reserva Federal muestran siete subidas de tipos durante el año, hasta terminar con un rango objetivo para los fondos federales del 4,25% al 4,50%.\n\nAlgunos activos especulativos experimentaron desinflaciones similares a las de una burbuja, pero la caída de un índice amplio durante un endurecimiento monetario rápido no demuestra que todo el mercado hubiera sido una burbuja. Distintos sectores pueden recibir diagnósticos diferentes al mismo tiempo.'],
        ['¿Cómo se pueden diagnosticar las condiciones actuales o recientes del mercado?', 'Primero determina si un índice amplio se encuentra en un mercado bajista confirmado y después evalúa por separado si existían señales de una burbuja antes de la caída o durante ella. Mantener separadas estas preguntas evita que una gran pérdida se convierta en una prueba retrospectiva de especulación.\n\nUtiliza esta secuencia:\n\n1. **Mide la caída.** ¿Ha caído un índice amplio aproximadamente un 20% desde un máximo de cierre reciente? Si es así, se aplica la etiqueta convencional de mercado bajista.\n2. **Comprueba las valoraciones previas a la caída.** ¿Eran extremas varias medidas de valoración en relación con un historial relevante?\n3. **Compara los precios con los fundamentales.** ¿Los beneficios y las expectativas de flujos de caja respaldaban razonablemente el nivel de precios anterior?\n4. **Examina el comportamiento y el apalancamiento.** ¿Los inversores se endeudaban agresivamente, perseguían a los ganadores recientes o ignoraban el riesgo?\n5. **Analiza la amplitud.** ¿El entusiasmo era generalizado o el índice dependía de un pequeño grupo de empresas?\n6. **Identifica el catalizador.** ¿La caída siguió a una reversión especulativa o una recesión, un cambio de política o un shock externo modificó los fundamentales?\n\nUna fuerte evidencia de burbuja sin una gran caída sugiere una posible burbuja dentro de un mercado alcista en curso. Una caída del 20% con poca evidencia previa de exceso se describe mejor como un mercado bajista sin burbuja. Una evidencia sólida de ambas condiciones es compatible con una burbuja que ha comenzado a estallar, aunque analistas razonables aún pueden discrepar.'],
        ['¿Qué deberían concluir los inversores a partir de las señales de una burbuja?', 'Las señales de una burbuja deberían cambiar la evaluación del riesgo y el rendimiento esperado, no generar la certeza de que un desplome sea inminente. Son elementos para tomar decisiones sobre la cartera, no instrucciones automáticas de venderlo todo.\n\nLos inversores no deberían concluir que todas las acciones están sobrevaloradas, que un indicador elevado puede identificar el máximo o que el efectivo está libre de riesgo después de la inflación. Una burbuja puede volverse más extrema antes de terminar, mientras que un mercado caro puede corregirse mediante años de crecimiento de los beneficios en lugar de sufrir un desplome repentino.\n\nEntre las respuestas más defendibles se incluyen revisar la concentración, reequilibrar hacia una asignación de activos elegida, limitar el apalancamiento y comprobar si las necesidades de gasto a corto plazo dependen de activos volátiles. FINRA señala que la diversificación puede reducir el riesgo de grandes pérdidas causadas por una concentración excesiva en un solo valor o clase de activos, aunque no puede evitar todas las pérdidas.'],
        ['¿Puede existir una burbuja durante un mercado alcista?', 'Sí. La mayoría de las burbujas se forman mientras los precios suben, por lo que un mercado puede cumplir simultáneamente la definición de mercado alcista y mostrar señales claras de advertencia de una burbuja.'],
        ['¿Puede un mercado bajista convertirse en una burbuja?', 'Un mercado en caída no se convierte por sí mismo en una burbuja, porque los términos describen condiciones diferentes. Una recuperación desde un mercado bajista puede desarrollar finalmente valoraciones y comportamientos especulativos, creando una nueva burbuja incluso antes de que todos los activos recuperen su máximo anterior.'],
        ['¿Cuánto puede durar una burbuja bursátil?', 'No existe una duración fija, porque la valoración puede mantenerse elevada mientras crecen los beneficios, la financiación sigue disponible y los inversores continúan aceptando hipótesis optimistas. Las burbujas suelen ser más fáciles de identificar retrospectivamente, por lo que la duración no puede utilizarse como una herramienta fiable de sincronización.'],
        ['¿Demuestra una caída del mercado del 20% que ha estallado una burbuja?', 'No. Una caída del 20% respalda la etiqueta convencional de mercado bajista, pero demostrar una burbuja requiere evidencia separada sobre la valoración, los fundamentales, el apalancamiento y el comportamiento de los inversores anteriores.'],
      ],
    },
  },
] as const;

export function articlePath(article: typeof articles[number], locale: Locale) {
  return locale === 'es' ? `/es/aprender/${article.slug.es}/` : `/learn/${article.slug.en}/`;
}

export function articleAlternatePath(article: typeof articles[number], locale: ArticleLocale) {
  return articlePath(article, locale === 'en' ? 'es' : 'en');
}
