export type Locale = 'en' | 'es' | 'ca' | 'de' | 'fr' | 'it' | 'ja';

export const localeMeta = {
  en: { label: 'EN', name: 'English', path: '/', intl: 'en-US', og: 'en_US' },
  es: { label: 'ES', name: 'Español', path: '/es/', intl: 'es-ES', og: 'es_ES' },
  ca: { label: 'CA', name: 'Català', path: '/ca/', intl: 'ca-ES', og: 'ca_ES' },
  de: { label: 'DE', name: 'Deutsch', path: '/de/', intl: 'de-DE', og: 'de_DE' },
  fr: { label: 'FR', name: 'Français', path: '/fr/', intl: 'fr-FR', og: 'fr_FR' },
  it: { label: 'IT', name: 'Italiano', path: '/it/', intl: 'it-IT', og: 'it_IT' },
  ja: { label: 'JA', name: '日本語', path: '/ja/', intl: 'ja-JP', og: 'ja_JP' }
} as const;

export const copy = {
  en: {
    lang: 'en', locale: 'en_US', path: '/', otherPath: '/es/', otherLabel: 'ES', otherName: 'Ver en español',
    title: 'Are We in a Stock Market Bubble? Live Bubble Indicators',
    description: 'Is the market in a bubble? Check Shiller CAPE, market value to GDP, margin debt, household equity allocation, credit spreads and VIX daily.',
    image: '/og-en.png', imageAlt: 'Are we in a stock market bubble? A daily market risk dashboard.',
    wordmark: 'ARE WE IN A BUBBLE YET?', homeLabel: 'Are we in a bubble yet? home',
    freshness: 'DATA CHECKED DAILY', shortAnswer: 'THE SHORT ANSWER',
    verdict: { YES: 'YES', PROBABLY: 'PROBABLY', MAYBE: 'MAYBE', NOT_YET: 'NOT YET', NO: 'NO' },
    summaries: {
      YES: 'The evidence is broad and unusually stretched. This looks like bubble territory, even if no gauge can call the top.',
      PROBABLY: 'Several independent warning signs are flashing. The market looks more bubbly than merely expensive.',
      MAYBE: 'The evidence is genuinely mixed. Some gauges are hot, while others have not joined the party.',
      NOT_YET: 'A few ingredients are warming up, but the full bubble recipe is not in the oven yet.',
      NO: 'Valuation, leverage, positioning and risk appetite are not jointly showing bubble conditions.'
    },
    scoreAria: 'Stock market bubble pressure score', scoreLabel: 'COMPOSITE PRESSURE', cool: 'COOL', stretched: 'STRETCHED', bubble: 'BUBBLE',
    scoreCopy: 'Valuation and leverage account for 70% of the score.', readEvidence: 'READ THE EVIDENCE',
    confidenceLabel: 'DECISION CONFIDENCE', confidenceHigh: 'HIGH AGREEMENT', confidenceMedium: 'MIXED AGREEMENT', confidenceLow: 'LOW AGREEMENT',
    confidenceHelp: 'Measures signal agreement and distance from a decision boundary—not the odds of a crash.',
    confidenceCopy: { high: 'The gauges mostly tell the same story.', medium: 'The gauges agree directionally, with meaningful dissent.', low: 'The gauges disagree. Treat the headline with extra caution.' },
    evidenceKicker: 'THE EVIDENCE', evidenceTitle: ['Six signals.', 'One honest read.'],
    evidenceIntro: 'No single metric can call a market top. We combine valuation, leverage and household positioning with faster credit and sentiment signals.',
    risk: 'RISK', low: 'LOW', high: 'HIGH', trend: 'HISTORICAL TREND', asOf: 'AS OF', sourceSuffix: 'SOURCE',
    methodKicker: 'HOW TO READ THIS', methodTitle: ['A temperature check,', 'not a crystal ball.'],
    methodP1: 'This stock market bubble score measures how closely today resembles historically overheated US equity markets. It does not predict when prices will turn—or whether they must.',
    methodP2: 'Each indicator is normalized from 0–100 against transparent thresholds, then weighted toward fundamentals: valuation 45%, leverage 25%, positioning 10%, credit 12%, sentiment 8%.',
    aboutKicker: 'WHAT THE SCORE MEANS', aboutTitle: 'Are we in a stock market bubble?',
    aboutVerdict: { YES: 'The evidence says yes.', PROBABLY: 'The evidence says probably.', MAYBE: 'The evidence is mixed.', NOT_YET: 'The evidence says not yet.', NO: 'The evidence says no.' },
    aboutP1: 'A bubble is not simply a market at an all-time high. It is a market where prices, leverage and confidence detach from the economic fundamentals beneath them. The composite score shows how strongly those conditions align today.',
    aboutP2: 'The Shiller CAPE and market-value-to-GDP ratio measure valuation. FINRA margin debt measures leverage. Household equity allocation captures positioning, while credit spreads and the VIX measure risk appetite.',
    disclaimer: 'Built from public data. Not investment advice.', methodology: 'METHODOLOGY & DATA', explore: 'EXPLORE THE SIGNALS',
    updatedLabel: 'Last updated', datasetName: 'US stock market bubble indicators',
    datasetDescription: 'A daily-updated collection of US stock market valuation, leverage, positioning, credit and sentiment indicators.',
    articleTitles: ['How to spot a stock market bubble', 'What is the Shiller CAPE ratio?', 'Margin debt and stock market bubbles', 'How our bubble indicator works']
  },
  es: {
    lang: 'es', locale: 'es_ES', path: '/es/', otherPath: '/', otherLabel: 'EN', otherName: 'View in English',
    title: '¿Hay una burbuja bursátil? Indicadores actualizados',
    description: '¿Hay una burbuja bursátil? Consulta CAPE de Shiller, valor de mercado/PIB, deuda de margen, asignación familiar, crédito y VIX a diario.',
    image: '/og-es.png', imageAlt: '¿Hay una burbuja bursátil? Panel diario de riesgo de mercado.',
    wordmark: '¿ESTAMOS EN UNA BURBUJA?', homeLabel: '¿Estamos en una burbuja? inicio',
    freshness: 'DATOS REVISADOS A DIARIO', shortAnswer: 'LA RESPUESTA CORTA',
    verdict: { YES: 'SÍ', PROBABLY: 'PROBABLEMENTE', MAYBE: 'QUIZÁ', NOT_YET: 'TODAVÍA NO', NO: 'NO' },
    summaries: {
      YES: 'La evidencia es amplia y está excepcionalmente tensionada. Esto parece territorio de burbuja, aunque ningún indicador puede anticipar el techo.',
      PROBABLY: 'Varias señales independientes están en alerta. El mercado parece más burbujeante que simplemente caro.',
      MAYBE: 'La evidencia es realmente mixta. Algunos indicadores están calientes y otros todavía no se han unido a la fiesta.',
      NOT_YET: 'Algunos ingredientes se están calentando, pero la receta completa de la burbuja aún no está en el horno.',
      NO: 'La valoración, el apalancamiento, el posicionamiento y el apetito por el riesgo no apuntan conjuntamente a una burbuja.'
    },
    scoreAria: 'Índice de presión de burbuja bursátil', scoreLabel: 'PRESIÓN COMPUESTA', cool: 'CALMA', stretched: 'TENSIÓN', bubble: 'BURBUJA',
    scoreCopy: 'La valoración y el apalancamiento representan el 70% de la puntuación.', readEvidence: 'VER LA EVIDENCIA',
    confidenceLabel: 'CONFIANZA EN LA DECISIÓN', confidenceHigh: 'ACUERDO ALTO', confidenceMedium: 'ACUERDO MIXTO', confidenceLow: 'ACUERDO BAJO',
    confidenceHelp: 'Mide el acuerdo entre señales y la distancia a un umbral, no la probabilidad de una caída.',
    confidenceCopy: { high: 'Los indicadores cuentan casi la misma historia.', medium: 'Los indicadores coinciden en la dirección, pero hay discrepancias relevantes.', low: 'Los indicadores discrepan. Conviene tomar el titular con más cautela.' },
    evidenceKicker: 'LA EVIDENCIA', evidenceTitle: ['Seis señales.', 'Una lectura honesta.'],
    evidenceIntro: 'Ninguna métrica puede anticipar por sí sola un techo de mercado. Combinamos valoración, apalancamiento y posicionamiento con señales más rápidas de crédito y sentimiento.',
    risk: 'RIESGO', low: 'BAJO', high: 'ALTO', trend: 'TENDENCIA HISTÓRICA', asOf: 'DATOS DE', sourceSuffix: 'FUENTE',
    methodKicker: 'CÓMO INTERPRETARLO', methodTitle: ['Un termómetro,', 'no una bola de cristal.'],
    methodP1: 'Este índice de burbuja bursátil mide cuánto se parece el mercado estadounidense actual a periodos históricamente sobrecalentados. No predice cuándo caerán los precios, ni afirma que tengan que hacerlo.',
    methodP2: 'Cada indicador se normaliza de 0 a 100 con umbrales transparentes. La ponderación prioriza los fundamentales: valoración 45%, apalancamiento 25%, posicionamiento 10%, crédito 12% y sentimiento 8%.',
    aboutKicker: 'QUÉ SIGNIFICA EL ÍNDICE', aboutTitle: '¿Hay una burbuja en la bolsa?',
    aboutVerdict: { YES: 'La evidencia dice que sí.', PROBABLY: 'La evidencia dice que probablemente.', MAYBE: 'La evidencia es mixta.', NOT_YET: 'La evidencia dice que todavía no.', NO: 'La evidencia dice que no.' },
    aboutP1: 'Una burbuja no es simplemente un mercado en máximos históricos. Aparece cuando los precios, el apalancamiento y la confianza se separan de los fundamentos económicos. El índice compuesto muestra cuánto coinciden hoy esas condiciones.',
    aboutP2: 'El CAPE de Shiller y el valor de mercado frente al PIB miden la valoración. La deuda de margen de FINRA mide el apalancamiento. La asignación familiar a bolsa captura el posicionamiento; los diferenciales y el VIX miden el apetito por el riesgo.',
    disclaimer: 'Creado con datos públicos. No es asesoramiento financiero.', methodology: 'METODOLOGÍA Y DATOS', explore: 'EXPLORA LAS SEÑALES',
    updatedLabel: 'Última actualización', datasetName: 'Indicadores de burbuja bursátil en Estados Unidos',
    datasetDescription: 'Colección diaria de indicadores de valoración, apalancamiento, posicionamiento, crédito y sentimiento del mercado bursátil estadounidense.',
    articleTitles: ['Cómo detectar una burbuja bursátil', '¿Qué es el ratio CAPE de Shiller?', 'Deuda de margen y burbujas bursátiles', 'Cómo funciona el indicador de burbuja']
  },
  ca: {
    lang: 'ca', locale: 'ca_ES', path: '/ca/', otherPath: '/', otherLabel: 'EN', otherName: 'View in English',
    title: 'Hi ha una bombolla borsària? Indicadors en directe',
    description: 'Hi ha una bombolla al mercat? Consulta diàriament el CAPE de Shiller, valor de mercat/PIB, deute de marge, assignació, crèdit i VIX.',
    image: '/og-en.png', imageAlt: 'Hi ha una bombolla borsària? Tauler diari de risc de mercat.',
    wordmark: 'JA SOM EN UNA BOMBOLLA?', homeLabel: 'Inici: ja som en una bombolla?', freshness: 'DADES REVISADES DIÀRIAMENT', shortAnswer: 'RESPOSTA BREU',
    verdict: { YES: 'SÍ', PROBABLY: 'PROBABLEMENT', MAYBE: 'POTSER', NOT_YET: 'ENCARA NO', NO: 'NO' },
    summaries: { YES: 'L’evidència és àmplia i excepcionalment tensionada. Sembla territori de bombolla, encara que cap indicador pot marcar el màxim.', PROBABLY: 'Diversos senyals independents estan en alerta. El mercat sembla més bombollejant que simplement car.', MAYBE: 'L’evidència és realment mixta. Alguns indicadors estan calents i d’altres encara no s’hi han afegit.', NOT_YET: 'Alguns ingredients s’escalfen, però la recepta completa de la bombolla encara no és al forn.', NO: 'Valoració, palanquejament, posicionament i apetència pel risc no indiquen conjuntament una bombolla.' },
    scoreAria: 'Índex de pressió de bombolla borsària', scoreLabel: 'PRESSIÓ COMPOSTA', cool: 'CALMA', stretched: 'TENSIÓ', bubble: 'BOMBOLLA', scoreCopy: 'La valoració i el palanquejament representen el 70% de la puntuació.', readEvidence: 'VEURE L’EVIDÈNCIA',
    confidenceLabel: 'CONFIANÇA EN LA DECISIÓ', confidenceHigh: 'ACORD ALT', confidenceMedium: 'ACORD MIXT', confidenceLow: 'ACORD BAIX', confidenceHelp: 'Mesura l’acord entre senyals i la distància a un llindar, no la probabilitat d’una caiguda.', confidenceCopy: { high: 'Els indicadors expliquen gairebé la mateixa història.', medium: 'Els indicadors coincideixen en la direcció, amb discrepàncies importants.', low: 'Els indicadors discrepen. Cal interpretar el titular amb més prudència.' },
    evidenceKicker: 'L’EVIDÈNCIA', evidenceTitle: ['Sis senyals.', 'Una lectura honesta.'], evidenceIntro: 'Cap mètrica pot anticipar per si sola un màxim. Combinem valoració, palanquejament i posicionament amb senyals més ràpids de crèdit i sentiment.',
    risk: 'RISC', low: 'BAIX', high: 'ALT', trend: 'TENDÈNCIA HISTÒRICA', asOf: 'DADES DE', sourceSuffix: 'FONT', methodKicker: 'COM INTERPRETAR-HO', methodTitle: ['Un termòmetre,', 'no una bola de vidre.'], methodP1: 'Aquest índex mesura fins a quin punt el mercat nord-americà actual s’assembla a períodes històricament sobreescalfats. No prediu quan giraran els preus.', methodP2: 'Cada indicador es normalitza de 0 a 100 amb llindars transparents: valoració 45%, palanquejament 25%, posicionament 10%, crèdit 12% i sentiment 8%.',
    aboutKicker: 'QUÈ SIGNIFICA L’ÍNDEX', aboutTitle: 'Hi ha una bombolla a la borsa?', aboutVerdict: { YES: 'L’evidència diu que sí.', PROBABLY: 'L’evidència diu que probablement.', MAYBE: 'L’evidència és mixta.', NOT_YET: 'L’evidència diu que encara no.', NO: 'L’evidència diu que no.' }, aboutP1: 'Una bombolla no és només un mercat en màxims. Apareix quan preus, palanquejament i confiança se separen dels fonaments econòmics.', aboutP2: 'El CAPE i el valor de mercat/PIB mesuren valoració; el deute de marge, palanquejament; l’assignació, els diferencials i el VIX completen la lectura.',
    disclaimer: 'Creat amb dades públiques. No és assessorament financer.', methodology: 'METODOLOGIA I DADES', explore: 'EXPLORA ELS SENYALS', updatedLabel: 'Darrera actualització', datasetName: 'Indicadors de bombolla borsària dels EUA', datasetDescription: 'Col·lecció diària d’indicadors de valoració, palanquejament, posicionament, crèdit i sentiment.', articleTitles: ['Com detectar una bombolla borsària', 'Què és el CAPE de Shiller?', 'Deute de marge i bombolles borsàries', 'Com funciona l’indicador de bombolla']
  },
  de: {
    lang: 'de', locale: 'de_DE', path: '/de/', otherPath: '/', otherLabel: 'EN', otherName: 'View in English',
    title: 'Ist der Aktienmarkt in einer Blase? Live-Indikatoren', description: 'Ist der Markt in einer Blase? Prüfen Sie täglich Shiller-CAPE, Marktwert/BIP, Margin Debt, Aktienquote, Kreditspreads und VIX.', image: '/og-en.png', imageAlt: 'Ist der Aktienmarkt in einer Blase? Tägliches Marktrisiko-Dashboard.',
    wordmark: 'SIND WIR SCHON IN EINER BLASE?', homeLabel: 'Startseite: Sind wir in einer Blase?', freshness: 'DATEN TÄGLICH GEPRÜFT', shortAnswer: 'DIE KURZE ANTWORT', verdict: { YES: 'JA', PROBABLY: 'WAHRSCHEINLICH', MAYBE: 'VIELLEICHT', NOT_YET: 'NOCH NICHT', NO: 'NEIN' },
    summaries: { YES: 'Die Evidenz ist breit und ungewöhnlich überdehnt. Das sieht nach Blasenterritorium aus, auch wenn kein Indikator den Höchststand vorhersagen kann.', PROBABLY: 'Mehrere unabhängige Warnsignale blinken. Der Markt wirkt eher blasig als nur teuer.', MAYBE: 'Die Evidenz ist wirklich gemischt. Einige Indikatoren sind heiß, andere machen noch nicht mit.', NOT_YET: 'Einige Zutaten erwärmen sich, aber das vollständige Blasenrezept ist noch nicht im Ofen.', NO: 'Bewertung, Verschuldung, Positionierung und Risikobereitschaft zeigen nicht gemeinsam Blasenbedingungen.' },
    scoreAria: 'Druckwert für eine Aktienmarktblase', scoreLabel: 'GESAMTDRUCK', cool: 'KÜHL', stretched: 'ÜBERDEHNT', bubble: 'BLASE', scoreCopy: 'Bewertung und Verschuldung machen 70% des Werts aus.', readEvidence: 'EVIDENZ ANSEHEN', confidenceLabel: 'ENTSCHEIDUNGSSICHERHEIT', confidenceHigh: 'HOHE ÜBEREINSTIMMUNG', confidenceMedium: 'GEMISCHTE ÜBEREINSTIMMUNG', confidenceLow: 'NIEDRIGE ÜBEREINSTIMMUNG', confidenceHelp: 'Misst Signalübereinstimmung und Abstand zur Entscheidungsgrenze – nicht die Wahrscheinlichkeit eines Crashs.', confidenceCopy: { high: 'Die Indikatoren erzählen weitgehend dieselbe Geschichte.', medium: 'Die Richtung stimmt überein, aber es gibt deutliche Gegenstimmen.', low: 'Die Indikatoren widersprechen sich. Die Schlagzeile ist mit Vorsicht zu lesen.' },
    evidenceKicker: 'DIE EVIDENZ', evidenceTitle: ['Sechs Signale.', 'Eine ehrliche Einordnung.'], evidenceIntro: 'Kein einzelner Wert kann ein Markthoch vorhersagen. Wir kombinieren Bewertung, Verschuldung und Positionierung mit schnelleren Kredit- und Stimmungssignalen.', risk: 'RISIKO', low: 'NIEDRIG', high: 'HOCH', trend: 'HISTORISCHER VERLAUF', asOf: 'STAND', sourceSuffix: 'QUELLE',
    methodKicker: 'SO LESEN SIE DAS', methodTitle: ['Ein Temperaturcheck,', 'keine Kristallkugel.'], methodP1: 'Der Wert misst, wie stark der heutige US-Aktienmarkt historisch überhitzten Phasen ähnelt. Er sagt nicht voraus, wann die Kurse drehen.', methodP2: 'Jeder Indikator wird transparent auf 0–100 normiert: Bewertung 45%, Verschuldung 25%, Positionierung 10%, Kredit 12%, Stimmung 8%.', aboutKicker: 'WAS DER WERT BEDEUTET', aboutTitle: 'Ist der Aktienmarkt in einer Blase?', aboutVerdict: { YES: 'Die Evidenz sagt ja.', PROBABLY: 'Die Evidenz sagt wahrscheinlich.', MAYBE: 'Die Evidenz ist gemischt.', NOT_YET: 'Die Evidenz sagt noch nicht.', NO: 'Die Evidenz sagt nein.' }, aboutP1: 'Eine Blase ist nicht bloß ein Markt auf Rekordhoch. Sie entsteht, wenn Preise, Verschuldung und Zuversicht sich von den wirtschaftlichen Fundamentaldaten lösen.', aboutP2: 'Shiller-CAPE und Marktwert/BIP messen Bewertung. Margin Debt misst Verschuldung; Aktienquote, Kreditspreads und VIX ergänzen Positionierung und Risikobereitschaft.',
    disclaimer: 'Aus öffentlichen Daten. Keine Anlageberatung.', methodology: 'METHODIK UND DATEN', explore: 'SIGNALE ERKUNDEN', updatedLabel: 'Zuletzt aktualisiert', datasetName: 'US-Aktienmarkt-Blasenindikatoren', datasetDescription: 'Täglich aktualisierte Indikatoren für Bewertung, Verschuldung, Positionierung, Kredit und Stimmung.', articleTitles: ['Eine Aktienmarktblase erkennen', 'Was ist das Shiller-CAPE?', 'Margin Debt und Aktienmarktblasen', 'So funktioniert unser Blasenindikator']
  },
  fr: {
    lang: 'fr', locale: 'fr_FR', path: '/fr/', otherPath: '/', otherLabel: 'EN', otherName: 'View in English', title: 'Sommes-nous dans une bulle boursière ? Indicateurs', description: 'Le marché est-il dans une bulle ? Consultez chaque jour le CAPE de Shiller, valeur/PIB, dette sur marge, allocation, crédit et VIX.', image: '/og-en.png', imageAlt: 'Sommes-nous dans une bulle boursière ? Tableau de risque quotidien.', wordmark: 'SOMMES-NOUS DÉJÀ DANS UNE BULLE ?', homeLabel: 'Accueil : sommes-nous dans une bulle ?', freshness: 'DONNÉES VÉRIFIÉES CHAQUE JOUR', shortAnswer: 'LA RÉPONSE COURTE', verdict: { YES: 'OUI', PROBABLY: 'PROBABLEMENT', MAYBE: 'PEUT-ÊTRE', NOT_YET: 'PAS ENCORE', NO: 'NON' },
    summaries: { YES: 'Les preuves sont nombreuses et exceptionnellement tendues. Cela ressemble à une bulle, même si aucun indicateur ne peut dater le sommet.', PROBABLY: 'Plusieurs signaux indépendants clignotent. Le marché paraît davantage en bulle que simplement cher.', MAYBE: 'Les preuves sont réellement partagées. Certains indicateurs chauffent, d’autres restent à l’écart.', NOT_YET: 'Quelques ingrédients chauffent, mais la recette complète de la bulle n’est pas encore au four.', NO: 'Valorisation, levier, positionnement et appétit pour le risque ne signalent pas ensemble une bulle.' }, scoreAria: 'Score de pression de bulle boursière', scoreLabel: 'PRESSION COMPOSITE', cool: 'CALME', stretched: 'TENDU', bubble: 'BULLE', scoreCopy: 'La valorisation et le levier représentent 70% du score.', readEvidence: 'VOIR LES PREUVES', confidenceLabel: 'CONFIANCE DANS LA DÉCISION', confidenceHigh: 'FORTE CONCORDANCE', confidenceMedium: 'CONCORDANCE MITIGÉE', confidenceLow: 'FAIBLE CONCORDANCE', confidenceHelp: 'Mesure la concordance des signaux et la distance au seuil, pas la probabilité d’un krach.', confidenceCopy: { high: 'Les indicateurs racontent presque tous la même histoire.', medium: 'Les indicateurs vont dans le même sens, avec des désaccords notables.', low: 'Les indicateurs divergent. Interprétez le titre avec davantage de prudence.' },
    evidenceKicker: 'LES PREUVES', evidenceTitle: ['Six signaux.', 'Une lecture honnête.'], evidenceIntro: 'Aucun indicateur ne peut dater seul un sommet. Nous combinons valorisation, levier et positionnement avec des signaux plus rapides de crédit et de sentiment.', risk: 'RISQUE', low: 'FAIBLE', high: 'ÉLEVÉ', trend: 'TENDANCE HISTORIQUE', asOf: 'AU', sourceSuffix: 'SOURCE', methodKicker: 'COMMENT LE LIRE', methodTitle: ['Un thermomètre,', 'pas une boule de cristal.'], methodP1: 'Ce score mesure la ressemblance du marché américain actuel avec les périodes historiquement surchauffées. Il ne prédit pas le retournement des cours.', methodP2: 'Chaque indicateur est normalisé de 0 à 100 : valorisation 45%, levier 25%, positionnement 10%, crédit 12% et sentiment 8%.', aboutKicker: 'CE QUE SIGNIFIE LE SCORE', aboutTitle: 'Le marché est-il dans une bulle ?', aboutVerdict: { YES: 'Les preuves disent oui.', PROBABLY: 'Les preuves disent probablement.', MAYBE: 'Les preuves sont partagées.', NOT_YET: 'Les preuves disent pas encore.', NO: 'Les preuves disent non.' }, aboutP1: 'Une bulle n’est pas simplement un marché au plus haut. Elle apparaît lorsque prix, levier et confiance se détachent des fondamentaux économiques.', aboutP2: 'Le CAPE et la valeur de marché/PIB mesurent la valorisation. La dette sur marge mesure le levier ; allocation, spreads et VIX complètent la lecture.', disclaimer: 'Construit avec des données publiques. Pas un conseil financier.', methodology: 'MÉTHODOLOGIE ET DONNÉES', explore: 'EXPLORER LES SIGNAUX', updatedLabel: 'Dernière mise à jour', datasetName: 'Indicateurs de bulle du marché américain', datasetDescription: 'Indicateurs quotidiens de valorisation, levier, positionnement, crédit et sentiment.', articleTitles: ['Comment repérer une bulle boursière', 'Qu’est-ce que le CAPE de Shiller ?', 'Dette sur marge et bulles boursières', 'Comment fonctionne notre indicateur']
  },
  it: {
    lang: 'it', locale: 'it_IT', path: '/it/', otherPath: '/', otherLabel: 'EN', otherName: 'View in English', title: 'Siamo in una bolla azionaria? Indicatori aggiornati', description: 'Il mercato è in una bolla? Controlla ogni giorno CAPE di Shiller, valore/PIL, debito a margine, allocazione, credito e VIX.', image: '/og-en.png', imageAlt: 'Siamo in una bolla azionaria? Dashboard quotidiana del rischio.', wordmark: 'SIAMO GIÀ IN UNA BOLLA?', homeLabel: 'Home: siamo in una bolla?', freshness: 'DATI CONTROLLATI OGNI GIORNO', shortAnswer: 'LA RISPOSTA BREVE', verdict: { YES: 'SÌ', PROBABLY: 'PROBABILMENTE', MAYBE: 'FORSE', NOT_YET: 'NON ANCORA', NO: 'NO' },
    summaries: { YES: 'Le prove sono ampie ed eccezionalmente tese. Sembra territorio da bolla, anche se nessun indicatore può chiamare il massimo.', PROBABLY: 'Diversi segnali indipendenti lampeggiano. Il mercato sembra più in bolla che semplicemente costoso.', MAYBE: 'Le prove sono davvero miste. Alcuni indicatori sono caldi, altri non si sono ancora uniti.', NOT_YET: 'Alcuni ingredienti si stanno scaldando, ma la ricetta completa della bolla non è ancora in forno.', NO: 'Valutazione, leva, posizionamento e propensione al rischio non indicano insieme una bolla.' }, scoreAria: 'Indice di pressione della bolla azionaria', scoreLabel: 'PRESSIONE COMPOSITA', cool: 'CALMO', stretched: 'TESO', bubble: 'BOLLA', scoreCopy: 'Valutazione e leva rappresentano il 70% del punteggio.', readEvidence: 'VEDI LE PROVE', confidenceLabel: 'FIDUCIA NELLA DECISIONE', confidenceHigh: 'ACCORDO ELEVATO', confidenceMedium: 'ACCORDO MISTO', confidenceLow: 'ACCORDO BASSO', confidenceHelp: 'Misura l’accordo dei segnali e la distanza dalla soglia, non la probabilità di un crollo.', confidenceCopy: { high: 'Gli indicatori raccontano quasi la stessa storia.', medium: 'Gli indicatori concordano sulla direzione, con dissensi rilevanti.', low: 'Gli indicatori non concordano. Interpreta il titolo con maggiore cautela.' },
    evidenceKicker: 'LE PROVE', evidenceTitle: ['Sei segnali.', 'Una lettura onesta.'], evidenceIntro: 'Nessun indicatore può chiamare da solo un massimo. Combiniamo valutazione, leva e posizionamento con segnali più rapidi di credito e sentiment.', risk: 'RISCHIO', low: 'BASSO', high: 'ALTO', trend: 'ANDAMENTO STORICO', asOf: 'AL', sourceSuffix: 'FONTE', methodKicker: 'COME LEGGERLO', methodTitle: ['Un termometro,', 'non una sfera di cristallo.'], methodP1: 'Questo indice misura quanto il mercato statunitense di oggi assomigli a fasi storicamente surriscaldate. Non prevede quando i prezzi invertiranno.', methodP2: 'Ogni indicatore è normalizzato da 0 a 100: valutazione 45%, leva 25%, posizionamento 10%, credito 12% e sentiment 8%.', aboutKicker: 'COSA SIGNIFICA IL PUNTEGGIO', aboutTitle: 'Il mercato è in una bolla?', aboutVerdict: { YES: 'Le prove dicono di sì.', PROBABLY: 'Le prove dicono probabilmente.', MAYBE: 'Le prove sono miste.', NOT_YET: 'Le prove dicono non ancora.', NO: 'Le prove dicono no.' }, aboutP1: 'Una bolla non è semplicemente un mercato ai massimi. Nasce quando prezzi, leva e fiducia si separano dai fondamentali economici.', aboutP2: 'CAPE e valore di mercato/PIL misurano la valutazione. Il debito a margine misura la leva; allocazione, spread e VIX completano la lettura.', disclaimer: 'Basato su dati pubblici. Non è consulenza finanziaria.', methodology: 'METODOLOGIA E DATI', explore: 'ESPLORA I SEGNALI', updatedLabel: 'Ultimo aggiornamento', datasetName: 'Indicatori di bolla del mercato USA', datasetDescription: 'Indicatori quotidiani di valutazione, leva, posizionamento, credito e sentiment.', articleTitles: ['Come riconoscere una bolla azionaria', 'Cos’è il CAPE di Shiller?', 'Debito a margine e bolle azionarie', 'Come funziona il nostro indicatore']
  },
  ja: {
    lang: 'ja', locale: 'ja_JP', path: '/ja/', otherPath: '/', otherLabel: 'EN', otherName: 'View in English', title: '米国株はバブルなのか？ 最新バブル指標', description: '米国株はバブルか。シラーCAPE、時価総額対GDP、証拠金債務、家計の株式配分、信用スプレッド、VIXを毎日確認できます。', image: '/og-en.png', imageAlt: '米国株はバブルなのか。毎日更新の市場リスクダッシュボード。', wordmark: 'もうバブルなのか？', homeLabel: 'ホーム：もうバブルなのか？', freshness: 'データは毎日確認', shortAnswer: '短い答え', verdict: { YES: 'はい', PROBABLY: 'おそらく', MAYBE: '微妙', NOT_YET: 'まだ', NO: 'いいえ' },
    summaries: { YES: '複数の指標が広く、異例なほど過熱しています。天井の時期は分からなくても、バブル圏に見えます。', PROBABLY: '独立した複数の警告灯が点灯しています。単に割高というより、バブルに近い状態です。', MAYBE: '判断材料は割れています。過熱した指標もあれば、まだ冷静な指標もあります。', NOT_YET: '一部の材料は温まりつつありますが、バブルの条件はまだ揃っていません。', NO: '割高感、レバレッジ、投資配分、リスク選好が同時にバブル状態を示してはいません。' }, scoreAria: '株式市場のバブル圧力スコア', scoreLabel: '総合圧力', cool: '平常', stretched: '過熱', bubble: 'バブル', scoreCopy: '評価とレバレッジがスコアの70%を占めます。', readEvidence: '根拠を見る', confidenceLabel: '判定の信頼度', confidenceHigh: '高い一致', confidenceMedium: 'まちまちな一致', confidenceLow: '低い一致', confidenceHelp: '指標の一致度と判定境界までの距離を示します。暴落確率ではありません。', confidenceCopy: { high: '各指標はほぼ同じ状況を示しています。', medium: '方向性は一致していますが、無視できない反対材料があります。', low: '指標が食い違っています。見出しは慎重に解釈してください。' },
    evidenceKicker: '判断材料', evidenceTitle: ['6つの指標。', '一つの率直な判断。'], evidenceIntro: '単一の指標で市場の天井は分かりません。評価、レバレッジ、家計の配分に、信用とセンチメントの速い指標を組み合わせます。', risk: 'リスク', low: '低', high: '高', trend: '長期推移', asOf: '時点', sourceSuffix: '出典', methodKicker: '読み方', methodTitle: ['温度計であって、', '水晶玉ではない。'], methodP1: '現在の米国株市場が、歴史的な過熱局面にどれほど似ているかを測ります。価格がいつ反転するかは予測しません。', methodP2: '各指標を透明な基準で0〜100に正規化します。評価45%、レバレッジ25%、配分10%、信用12%、センチメント8%です。', aboutKicker: 'スコアの意味', aboutTitle: '米国株はバブルなのか？', aboutVerdict: { YES: '根拠は「はい」です。', PROBABLY: '根拠は「おそらく」です。', MAYBE: '根拠は割れています。', NOT_YET: '根拠は「まだ」です。', NO: '根拠は「いいえ」です。' }, aboutP1: '最高値を付けているだけではバブルではありません。価格、レバレッジ、自信が経済の基礎から離れるときにバブルが生まれます。', aboutP2: 'CAPEと時価総額対GDPは評価、証拠金債務はレバレッジ、家計配分、信用スプレッド、VIXはポジションとリスク選好を測ります。', disclaimer: '公開データを使用。投資助言ではありません。', methodology: '算出方法とデータ', explore: '指標を詳しく見る', updatedLabel: '最終更新', datasetName: '米国株式市場のバブル指標', datasetDescription: '評価、レバレッジ、ポジション、信用、センチメントを毎日更新するデータセット。', articleTitles: ['株式市場バブルの見分け方', 'シラーCAPEとは？', '証拠金債務と株式バブル', 'バブル指標の仕組み']
  }
} as const;

export const indicatorCopy = {
  es: {
    cape: { name: 'CAPE de Shiller', eyebrow: 'VALORACIÓN · 25% DEL ÍNDICE', description: 'Precio dividido por diez años de beneficios ajustados por inflación. Suaviza el ciclo económico para mostrar cuánto se paga por una capacidad de beneficio duradera.', threshold: 'Señal de burbuja por encima de 30×', change: 'Última lectura mensual' },
    buffett: { name: 'Valor de mercado / PIB', eyebrow: 'VALORACIÓN · 20% DEL ÍNDICE', description: 'Valor de las acciones estadounidenses frente a la producción económica anual. Indica cuánto paga el mercado por cada dólar que produce la economía.', threshold: 'Señal de burbuja por encima del 180%', change: 'Última lectura trimestral' },
    margin: { name: 'Deuda de margen', eyebrow: 'APALANCAMIENTO · 25% DEL ÍNDICE', description: 'Dinero que los clientes piden prestado contra sus valores. Un crecimiento rápido implica más apalancamiento y más ventas forzadas si los precios retroceden.', threshold: 'Riesgo alto por encima del 25% anual', change: 'VARIACIÓN_INTERANUAL' },
    allocation: { name: 'Asignación familiar a bolsa', eyebrow: 'POSICIONAMIENTO · 10% DEL ÍNDICE', description: 'Porcentaje de los activos financieros de los hogares invertido directa o indirectamente en acciones. Una asignación históricamente alta indica cuánto patrimonio depende ya de que la bolsa siga subiendo.', threshold: 'Extremo por encima del 45%', change: 'Última lectura trimestral' },
    credit: { name: 'Diferencial de crédito', eyebrow: 'CRÉDITO · 12% DEL ÍNDICE', description: 'Rentabilidad adicional que pagan las empresas estadounidenses con calificación Baa frente al bono del Tesoro a diez años. Un diferencial muy estrecho indica que los prestamistas perciben poco riesgo.', threshold: 'Complacencia por debajo del 1,80%', change: 'Los prestamistas perciben poco riesgo' },
    vix: { name: 'Volatilidad del mercado', eyebrow: 'SENTIMIENTO · 8% DEL ÍNDICE', description: 'El VIX refleja la volatilidad esperada a corto plazo del S&P 500. Lecturas excepcionalmente bajas pueden revelar complacencia entre los inversores.', threshold: 'Complacencia por debajo de 14', change: 'Calma, pero sin euforia' }
  },
  ca: {
    cape: { name: 'CAPE de Shiller', eyebrow: 'VALORACIÓ · 25% DEL PES', description: 'Preu dividit per deu anys de beneficis ajustats per inflació. Suavitza el cicle per mostrar quant es paga per una capacitat de benefici duradora.', threshold: 'Senyal de bombolla per sobre de 30×', change: 'Darrera lectura mensual' },
    buffett: { name: 'Valor de mercat / PIB', eyebrow: 'VALORACIÓ · 20% DEL PES', description: 'Valor de les accions nord-americanes respecte de la producció econòmica anual. Mostra quant paga el mercat per cada dòlar produït.', threshold: 'Senyal de bombolla per sobre del 180%', change: 'Darrera lectura trimestral' },
    margin: { name: 'Deute de marge', eyebrow: 'PALANQUEJAMENT · 25% DEL PES', description: 'Diners que els clients demanen prestats contra els seus valors. Un creixement ràpid implica més palanquejament i risc de vendes forçades.', threshold: 'Risc alt per sobre del 25% anual', change: 'YOY' },
    allocation: { name: 'Assignació familiar a borsa', eyebrow: 'POSICIONAMENT · 10% DEL PES', description: 'Percentatge dels actius financers de les llars invertit en accions. Una assignació històricament alta mostra quant patrimoni depèn de més pujades.', threshold: 'Extrem per sobre del 45%', change: 'Darrera lectura trimestral' },
    credit: { name: 'Diferencial de crèdit', eyebrow: 'CRÈDIT · 12% DEL PES', description: 'Rendibilitat addicional del deute corporatiu Baa respecte del Tresor a deu anys. Un diferencial estret indica que els prestadors perceben poc risc.', threshold: 'Complaença per sota de l’1,80%', change: 'Els prestadors perceben poc risc' },
    vix: { name: 'Volatilitat del mercat', eyebrow: 'SENTIMENT · 8% DEL PES', description: 'El VIX reflecteix la volatilitat esperada a curt termini de l’S&P 500. Lectures molt baixes poden revelar complaença.', threshold: 'Complaença per sota de 14', change: 'Calma, però sense eufòria' }
  },
  de: {
    cape: { name: 'Shiller-CAPE', eyebrow: 'BEWERTUNG · 25% GEWICHT', description: 'Kurs geteilt durch zehn Jahre inflationsbereinigter Gewinne. Glättet den Zyklus und zeigt, wie teuer dauerhafte Ertragskraft ist.', threshold: 'Blasensignal über 30×', change: 'Neuester Monatswert' },
    buffett: { name: 'Marktwert / BIP', eyebrow: 'BEWERTUNG · 20% GEWICHT', description: 'Wert der US-Aktien im Verhältnis zur jährlichen Wirtschaftsleistung. Zeigt, wie viel der Markt je produziertem Dollar bezahlt.', threshold: 'Blasensignal über 180%', change: 'Neuester Quartalswert' },
    margin: { name: 'Margin Debt', eyebrow: 'VERSCHULDUNG · 25% GEWICHT', description: 'Geld, das Anleger gegen Wertpapiere leihen. Schnelles Wachstum erhöht Hebel und das Risiko erzwungener Verkäufe.', threshold: 'Hohes Risiko über 25% jährlich', change: 'YOY' },
    allocation: { name: 'Aktienquote der Haushalte', eyebrow: 'POSITIONIERUNG · 10% GEWICHT', description: 'Anteil des Finanzvermögens der Haushalte in Aktien. Eine historisch hohe Quote zeigt, wie viel Vermögen von weiteren Kursgewinnen abhängt.', threshold: 'Extrem über 45%', change: 'Neuester Quartalswert' },
    credit: { name: 'Unternehmens-Kreditspread', eyebrow: 'KREDIT · 12% GEWICHT', description: 'Mehrrendite von US-Unternehmensanleihen mit Baa-Rating gegenüber zehnjährigen Staatsanleihen. Enge Spreads signalisieren geringe Risikowahrnehmung.', threshold: 'Sorglosigkeit unter 1,80%', change: 'Kreditgeber preisen wenig Risiko ein' },
    vix: { name: 'Marktvolatilität', eyebrow: 'STIMMUNG · 8% GEWICHT', description: 'Der VIX misst die erwartete kurzfristige Volatilität des S&P 500. Sehr niedrige Werte können Sorglosigkeit anzeigen.', threshold: 'Sorglosigkeit unter 14', change: 'Ruhig, aber nicht euphorisch' }
  },
  fr: {
    cape: { name: 'CAPE de Shiller', eyebrow: 'VALORISATION · POIDS 25%', description: 'Cours divisé par dix années de bénéfices corrigés de l’inflation. Lisse le cycle pour mesurer le prix d’une capacité bénéficiaire durable.', threshold: 'Signal de bulle au-dessus de 30×', change: 'Dernière lecture mensuelle' },
    buffett: { name: 'Valeur de marché / PIB', eyebrow: 'VALORISATION · POIDS 20%', description: 'Valeur des actions américaines rapportée à la production économique annuelle. Indique le prix payé pour chaque dollar produit.', threshold: 'Signal de bulle au-dessus de 180%', change: 'Dernière lecture trimestrielle' },
    margin: { name: 'Dette sur marge', eyebrow: 'LEVIER · POIDS 25%', description: 'Sommes empruntées par les clients contre leurs titres. Une croissance rapide augmente le levier et le risque de ventes forcées.', threshold: 'Risque élevé au-dessus de 25% par an', change: 'YOY' },
    allocation: { name: 'Allocation actions des ménages', eyebrow: 'POSITIONNEMENT · POIDS 10%', description: 'Part des actifs financiers des ménages investie en actions. Une allocation historiquement élevée révèle la dépendance à de nouvelles hausses.', threshold: 'Extrême au-dessus de 45%', change: 'Dernière lecture trimestrielle' },
    credit: { name: 'Spread de crédit', eyebrow: 'CRÉDIT · POIDS 12%', description: 'Rendement supplémentaire des obligations Baa par rapport au Trésor à dix ans. Un spread étroit indique peu de risque perçu.', threshold: 'Complaisance sous 1,80%', change: 'Les prêteurs intègrent peu de risque' },
    vix: { name: 'Volatilité du marché', eyebrow: 'SENTIMENT · POIDS 8%', description: 'Le VIX reflète la volatilité attendue à court terme du S&P 500. Des niveaux très faibles peuvent signaler la complaisance.', threshold: 'Complaisance sous 14', change: 'Calme, sans euphorie' }
  },
  it: {
    cape: { name: 'CAPE di Shiller', eyebrow: 'VALUTAZIONE · PESO 25%', description: 'Prezzo diviso per dieci anni di utili corretti per l’inflazione. Smussa il ciclo e mostra quanto si paga per una redditività durevole.', threshold: 'Segnale di bolla sopra 30×', change: 'Ultima lettura mensile' },
    buffett: { name: 'Valore di mercato / PIL', eyebrow: 'VALUTAZIONE · PESO 20%', description: 'Valore delle azioni USA rispetto alla produzione economica annua. Mostra quanto il mercato paga per ogni dollaro prodotto.', threshold: 'Segnale di bolla sopra il 180%', change: 'Ultima lettura trimestrale' },
    margin: { name: 'Debito a margine', eyebrow: 'LEVA · PESO 25%', description: 'Denaro preso in prestito contro i titoli. Una crescita rapida aumenta leva e rischio di vendite forzate.', threshold: 'Rischio elevato sopra il 25% annuo', change: 'YOY' },
    allocation: { name: 'Allocazione azionaria delle famiglie', eyebrow: 'POSIZIONAMENTO · PESO 10%', description: 'Quota delle attività finanziarie delle famiglie investita in azioni. Un livello storico elevato indica dipendenza da ulteriori rialzi.', threshold: 'Estremo sopra il 45%', change: 'Ultima lettura trimestrale' },
    credit: { name: 'Spread di credito', eyebrow: 'CREDITO · PESO 12%', description: 'Rendimento extra delle obbligazioni Baa rispetto al Treasury decennale. Uno spread stretto indica poco rischio percepito.', threshold: 'Compiacenza sotto l’1,80%', change: 'I finanziatori prezzano poco rischio' },
    vix: { name: 'Volatilità del mercato', eyebrow: 'SENTIMENT · PESO 8%', description: 'Il VIX riflette la volatilità attesa a breve dell’S&P 500. Valori molto bassi possono indicare compiacenza.', threshold: 'Compiacenza sotto 14', change: 'Calma, senza euforia' }
  },
  ja: {
    cape: { name: 'シラーCAPE', eyebrow: '評価 · ウェイト25%', description: '株価をインフレ調整後の10年平均利益で割った指標です。景気循環を平準化し、持続的な利益に対する価格を示します。', threshold: '30倍超でバブル警戒', change: '最新の月次値' },
    buffett: { name: '時価総額 / GDP', eyebrow: '評価 · ウェイト20%', description: '米国株の価値を年間の経済生産と比較します。経済が生む1ドルに市場がいくら払うかを示します。', threshold: '180%超でバブル警戒', change: '最新の四半期値' },
    margin: { name: '証拠金債務', eyebrow: 'レバレッジ · ウェイト25%', description: '保有証券を担保に投資家が借りる資金です。急増するとレバレッジと強制売却のリスクが高まります。', threshold: '前年比25%超で高リスク', change: 'YOY' },
    allocation: { name: '家計の株式配分', eyebrow: 'ポジション · ウェイト10%', description: '家計の金融資産に占める株式の割合です。歴史的な高水準は、資産がさらなる株高に依存していることを示します。', threshold: '45%超で極端', change: '最新の四半期値' },
    credit: { name: '信用スプレッド', eyebrow: '信用 · ウェイト12%', description: 'Baa社債と10年国債の利回り差です。差が非常に小さいと、貸し手がリスクを低く見ていることを示します。', threshold: '1.80%未満で楽観過剰', change: '貸し手はリスクを低く評価' },
    vix: { name: '市場ボラティリティ', eyebrow: 'センチメント · ウェイト8%', description: 'VIXはS&P 500の短期的な予想変動率を示します。極端に低い値は投資家の油断を示すことがあります。', threshold: '14未満で楽観過剰', change: '静かだが熱狂ではない' }
  }
} as const;

export const statusCopy = {
  en: { Extreme: 'Extreme', Elevated: 'Elevated', Complacent: 'Complacent', Neutral: 'Neutral' },
  es: { Extreme: 'Extremo', Elevated: 'Elevado', Complacent: 'Complaciente', Neutral: 'Neutral' },
  ca: { Extreme: 'Extrem', Elevated: 'Elevat', Complacent: 'Complaent', Neutral: 'Neutral' },
  de: { Extreme: 'Extrem', Elevated: 'Erhöht', Complacent: 'Sorglos', Neutral: 'Neutral' },
  fr: { Extreme: 'Extrême', Elevated: 'Élevé', Complacent: 'Complaisant', Neutral: 'Neutre' },
  it: { Extreme: 'Estremo', Elevated: 'Elevato', Complacent: 'Compiacente', Neutral: 'Neutrale' },
  ja: { Extreme: '極端', Elevated: '高い', Complacent: '楽観過剰', Neutral: '中立' }
} as const;

export const uiCopy = {
  en: { and: 'and', elevated: (n: number, total: number) => `${n} / ${total} signals are elevated.`, broad: (n: number, total: number, names: string) => `Pressure is broad: ${n} of ${total} signals are elevated, led by ${names}.`, concentrated: (names: string, cool: number) => `Pressure is concentrated in ${names}; ${cool} signals remain cooler.`, contained: (name: string) => `Most signals remain contained; ${name} is the main outlier.`, jump: 'Jump to each signal', weight: 'WEIGHT', buffett: 'THE BUFFETT INDICATOR', yoy: 'year over year', events: ['Dot-com', 'Credit crisis', 'COVID', 'Rate shock'] },
  es: { and: 'y', elevated: (n: number, total: number) => `${n} / ${total} señales están elevadas.`, broad: (n: number, total: number, names: string) => `La presión es amplia: ${n} de ${total} señales están elevadas, lideradas por ${names}.`, concentrated: (names: string, cool: number) => `La presión se concentra en ${names}; ${cool} señales permanecen más frías.`, contained: (name: string) => `La mayoría de señales siguen contenidas; ${name} es la principal excepción.`, jump: 'Ir a cada señal', weight: 'PESO', buffett: 'EL INDICADOR DE BUFFETT', yoy: 'interanual', events: ['Puntocom', 'Crisis de crédito', 'COVID', 'Shock de tipos'] },
  ca: { and: 'i', elevated: (n: number, total: number) => `${n} / ${total} senyals estan elevats.`, broad: (n: number, total: number, names: string) => `La pressió és àmplia: ${n} de ${total} senyals estan elevats, liderats per ${names}.`, concentrated: (names: string, cool: number) => `La pressió es concentra en ${names}; ${cool} senyals es mantenen més freds.`, contained: (name: string) => `La majoria de senyals continuen continguts; ${name} és l’excepció principal.`, jump: 'Anar a cada senyal', weight: 'PES', buffett: 'L’INDICADOR DE BUFFETT', yoy: 'interanual', events: ['Puntcom', 'Crisi de crèdit', 'COVID', 'Xoc de tipus'] },
  de: { and: 'und', elevated: (n: number, total: number) => `${n} / ${total} Signale sind erhöht.`, broad: (n: number, total: number, names: string) => `Der Druck ist breit: ${n} von ${total} Signalen sind erhöht, angeführt von ${names}.`, concentrated: (names: string, cool: number) => `Der Druck konzentriert sich auf ${names}; ${cool} Signale bleiben kühler.`, contained: (name: string) => `Die meisten Signale bleiben gedämpft; ${name} ist die wichtigste Ausnahme.`, jump: 'Zu jedem Signal springen', weight: 'GEWICHT', buffett: 'DER BUFFETT-INDIKATOR', yoy: 'zum Vorjahr', events: ['Dotcom', 'Kreditkrise', 'COVID', 'Zinsschock'] },
  fr: { and: 'et', elevated: (n: number, total: number) => `${n} / ${total} signaux sont élevés.`, broad: (n: number, total: number, names: string) => `La pression est large : ${n} signaux sur ${total} sont élevés, menés par ${names}.`, concentrated: (names: string, cool: number) => `La pression se concentre sur ${names} ; ${cool} signaux restent plus calmes.`, contained: (name: string) => `La plupart des signaux restent contenus ; ${name} est l’exception principale.`, jump: 'Aller à chaque signal', weight: 'POIDS', buffett: 'L’INDICATEUR DE BUFFETT', yoy: 'sur un an', events: ['Bulle Internet', 'Crise du crédit', 'COVID', 'Choc des taux'] },
  it: { and: 'e', elevated: (n: number, total: number) => `${n} / ${total} segnali sono elevati.`, broad: (n: number, total: number, names: string) => `La pressione è ampia: ${n} segnali su ${total} sono elevati, guidati da ${names}.`, concentrated: (names: string, cool: number) => `La pressione si concentra su ${names}; ${cool} segnali restano più freddi.`, contained: (name: string) => `La maggior parte dei segnali resta contenuta; ${name} è l’eccezione principale.`, jump: 'Vai a ciascun segnale', weight: 'PESO', buffett: 'L’INDICATORE DI BUFFETT', yoy: 'su base annua', events: ['Dot-com', 'Crisi del credito', 'COVID', 'Shock dei tassi'] },
  ja: { and: 'と', elevated: (n: number, total: number) => `${total}指標中${n}指標が高水準です。`, broad: (n: number, total: number, names: string) => `圧力は広範です。${total}指標中${n}指標が高水準で、${names}が主導しています。`, concentrated: (names: string, cool: number) => `圧力は${names}に集中し、${cool}指標は比較的落ち着いています。`, contained: (name: string) => `大半の指標は落ち着いており、主な例外は${name}です。`, jump: '各指標へ移動', weight: 'ウェイト', buffett: 'バフェット指標', yoy: '前年比', events: ['ドットコム', '信用危機', 'COVID', '利上げショック'] }
} as const;
